### ISSUE TITLE
Erreur si le champ valeur_attribut de la vue atlas.vm_cor_taxon_attribut est NULL

### ISSUE THREAD

**Issue by mathieubossaert** [PnX-SI/GeoNature-atlas#119]
L'erreur est renvoyée par le scipt /main/modeles/repositories/vmCorTaxonAttribut.py

Je vous de réécrire la requête comme ceci, ligne 9 du script : 

```sql
SELECT id_attribut, COALESCE(valeur_attribut, '') AS valeur_attribut, cd_ref 
FROM atlas.vm_cor_taxon_attribut \
```

**Comment by camillemonchicourt** [comment]
J'ai pas compris le problème ? Titre incomplet ?

**Comment by mathieubossaert** [comment]
Titre complet mais pas très
![erreur_valeur_attribut](https://user-images.githubusercontent.com/1642645/29822262-221468d4-8ccb-11e7-9ebd-49b40ac2fce2.png)
 clair. J'ai rencontré une erreur en voulant accéder aux fiches espèces.
Si le champ valeur_attribut de la vue atlas.vm_cor_taxon_attribut est NULL, l'erreur se produit.
Pour résoudre le souci, je propose plutôt que de stocker dans la VM un chaîne vide, d'utiliser COALESCE dans la requête.

**Comment by camillemonchicourt** [comment]
OK je vois. 
En effet on n'a jamais eu ce problème car cette VM basée sur une table de correspondance N-N n'a pas de raison d'être nulle. Soit on a l'info d'un attribut sur un taxon, soit on l'a pas et y a pas de ligne pour le CDREF. 
Mais en effet on pourrait ajouter cette sécurité.

**Comment by mathieubossaert** [comment]
Mais pour démarrer je n'ai aucune info. Et sauf erreur de ma part la VM est vide ça plante toute l'appli.

**Comment by camillemonchicourt** [comment]
Non si tu n'as aucune info, cette vm ne devrait renvoyer aucune ligne. C'est une table de correspondance entre les taxons et leurs attributs. Si aucun attribut renseigné, alors le vm ne devrait comporter aucune ligne.

**Comment by mathieubossaert** [comment]
Yep tu as raison. Si la table est vide ça fonctionne.

**Comment by camillemonchicourt** [comment]
:+1:
