### ISSUE TITLE
MEDIAS - Ajouter l'auteur

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-atlas#122]
Au niveau des vidéos et des audios, on affiche le titre du médias mais ça serait bien d'ajouter aussi l'auteur. Et éventuellement la description ?

**Comment by amandine-sahl** [comment]
Pour l'instant peu de mise en forme (à voir si suffisant)

![image](https://user-images.githubusercontent.com/3088650/58236380-12035580-7d43-11e9-8e0c-9f8e916badfe.png)

**Comment by camillemonchicourt** [comment]
Oui super, on affinera si besoin. Merci.
