### ISSUE TITLE
Verrouillage de la carte sur le territoire

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-atlas#145]
Sur les cartes, proposition de verrouillage de la zone d'affichage de la carte sur l'emprise du territoire (setMaxBounds).

```javascript
    // Add limits of the territory to the map
    $(document).ready(function () {
        $.getJSON(url_limit_territory, function (json) {
            var territoryLayer = L.geoJson(json, {
                style: territoryStyle
            });
            territoryLayer.addTo(map);
            map.setMaxBounds(territoryLayer.getBounds());
        });
    });
```

**Comment by camillemonchicourt** [comment]
Pourquoi pas, surtout si c'est associé à un paramètre pour activer/desactiver ce comportement.

**Comment by lpofredc** [comment]
Pas encore mais oui, c'est réalisable.

**Comment by RomainBaghi** [comment]
Je m'aperçois que `setMaxBounds ` ne verrouille pas vraiment mais ramène la carte systématiquement sur le territoire. En supplément, je rajouterai un paramètre `minZoom` pour bloquer le dezoom,  c'est à dire pour que l'on ne puisse pas trop s'éloigner du territoire (et avoir plusieurs fois la planète sur la carte!). 
```
// Map initialization
  firstMapTile = L.tileLayer(configuration.MAP.FIRST_MAP.url, {
    attribution: configuration.MAP.FIRST_MAP.attribution,
    minZoom: configuration.MAP.FIRST_MAP.minzoom
  });
  orthoMap = L.tileLayer(configuration.MAP.SECOND_MAP.url, {
    attribution: configuration.MAP.SECOND_MAP.attribution,
    minZoom: configuration.MAP.SECOND_MAP.minzoom
  });
```

**Comment by TheoLechemia** [comment]
Est-ce que c'est vraiment nécessaire de mettre le "min_zoom" sur la 1ere et la 2ème carte ? Ce sera toujours le même à priori ?
je ferais juste un MAP.MIN_ZOOM (avec des belles majuscule ;) )

**Comment by RomainBaghi** [comment]
non pas vraiment nécessaire :) de le mettre sur les deux cartes.
Je me demande si le fait de changer le fond carto change les incréments de zoom, si c'est le cas, alors cela peut être utile, sinon non.
Va pour les majuscules !

**Comment by TheoLechemia** [comment]
Le niveau de zoom est celui de leaflet, donc toujours le même

**Comment by camillemonchicourt** [comment]
Fait par @jbdesbas (https://github.com/PnX-SI/GeoNature-atlas/pull/201) et intégré dans la 1.4.0, avec par défaut l'étendue mondiale pour ne pas limiter. 

https://github.com/PnX-SI/GeoNature-atlas/blob/master/atlas/configuration/config.py.example#L55
