### ISSUE TITLE
Version Werkzeug à mettre à jour ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-atlas#147]
Un utilisateur a rencontré un problème lors de l'installation sur une Debian 8.10.

Erreur répétée dans le fichier `/tmp/errors_atlas.log` :
```
from werkzeug.wsgi import DispatcherMiddleware, ProxyMiddleware
ImportError: cannot import name ProxyMiddleware
```

Réglé en faisant `pip install --upgrade` dans le virtual env. Et qui fait alors passer à Werkzeug==0.14.1 au lieu de 0.11.11 indiqué dans https://github.com/PnEcrins/GeoNature-atlas/blob/master/requirements.txt

**Comment by RomainBaghi** [comment]
Réglé en faisant "pip install --upgrade werkzeug"

**Comment by camillemonchicourt** [comment]
Werkzeug mis à jour de la 0.11.11 à la version 0.15.4 dans la version 1.4.0 de GeoNature-atlas.
