### ISSUE TITLE
Ajouter parametre DISPLAY_OBSERVER

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-atlas#150]
Qui masquerait ou afficherait le bloc observateur des fiches espèces et des tooltip observation. 
RGPD oblige....

**Comment by mvergez** [comment]
Suite à une demande du PNR du Golfe du Morbihan, nous nous en sommes occupés avec @MathildeNS, ça vous va si je fais une PR ?

**Comment by lpofredc** [comment]
N'est pas ce que fait déjà le paramètre `ANONYMIZE` ?

https://github.com/PnX-SI/GeoNature-atlas/search?q=ANONYMIZE

**Comment by mvergez** [comment]
`ANONYMIZE` agit aussi sur les organismes je crois. Je vérifie ça

**Comment by TheoLechemia** [comment]
Hum, je rejoins Fred, `ANONYMIZE` masquait déjà les observateurs non ?  
https://github.com/PnX-SI/GeoNature-atlas/blob/4e5aebc486519f827666eb7fd40a0357c77b93ae/atlas/templates/speciesSheet/otherInformations.html#L98

**Comment by mvergez** [comment]
Je m'en occupe cet aprem
