### ISSUE TITLE
Espèces recherchées mais non observées

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-atlas#165]
Il serait intéressant de considérer distinctement dans les différentes restitution de geonature-atlas les espèces absentes malgré des recherches. 

- Au plus simple, en la retirant tout simplement de la vue matérialisée vm_observations (`where id_nomenclature_observation_status != 87`) des synthèses. 
- Bien plus complexe, en les faisant figuré sur les synthèses (si uniquement des données d'absence) mais avec un style spécifique à ces données (à la maille,  dans les tableaux).

Cas typique en Auvergne-Rhône-Alpes, la Loutre où la plupart des principaux cours d'eau ont été prospectés avec beaucoup d'absences.

**Comment by gildeluermoz** [comment]
La position de chacune des structures n'est pas la même sur la gestion et l'affichage des absences.
La solution 1 me semble donc la plus pertinente. Elle devrait être proposée par défaut dans la vue.
De mon point de vue, un atlas n'a pas vocation à afficher de l'absence. Le public ne va pas comprendre ça. Caractériser l'absence relève en effet de protocoles très différents, parfois sujet à caution, et dont l'interprétation nécessite d'en exposer le contexte. Il ne me semble pas possible de synthétiser le sens de l'information "absence" dans un outil grand public.
De plus, comment faire comprendre que là il y en a, là il n'y en avait pas (lorsqu'on a chercher, dans tel contexte et selon telle méthode, etc...) et là on ne sait pas (le reste du monde !).
Ce sujet est un sujet pour experts, très scientifique et non grand public ; en tout cas pas dans un outil très général comme l'atlas.

**Comment by camillemonchicourt** [comment]
Oui je suis bien d'accord.
Je pense qu'il faut les retirer de la vm_observations.

**Comment by camillemonchicourt** [comment]
Dans la version 1.4.0, compatible avec GeoNature V2, par défaut on ne prend que les données présentes : https://github.com/PnX-SI/GeoNature-atlas/blob/1.4.0/data/gn2/atlas_synthese.sql#L36

Il est possible de modifier la vue ``synthese.syntheseff`` pour prendre aussi les données d'absence et de customiser l'affichage des points et une légende pour dissocier les types de données, grâce au fichier ``static/custom/maps-custom.js`` (voir la doc https://github.com/PnX-SI/GeoNature-atlas/blob/master/docs/installation.rst#customisation-de-lapplication)
