### ISSUE TITLE
Moteur de recherche espèce : nom français en premier

### ISSUE THREAD

**Issue by sig-pnrnm** [PnX-SI/GeoNature-atlas#167]
Avant de me lancer dans cette adaptation souhaitée sur notre portail, je me permets une nouvelle fois de faire part ici de cette suggestion d'amélioration.

La liste déroulante du moteur de recherche espèce affiche actuellement les résultats sous la forme : 
`Nom latin | Nom français`
(ou plutôt `Nom latin | Nom vernaculaire` devrais-je écrire)

Pour notre instance, il est souhaité que cette liste affiche le nom français en premier.

En effet, si on s'entend bien sur le fait que l'Atlas vise en premier lieu le grand public, il paraît évident qu'il ne faut pas le noyer dans le latin tout de suite (même si le latin est évidemment important à conserver, ne serait-ce que pour la question des synonymes vernaculaires).

![recherche_busard](https://user-images.githubusercontent.com/26482054/47779256-faa64180-dcf8-11e8-929d-a6d0fe79013e.png)

Dans l'idéal, un peu de mise en forme serait même assez sympathique pour cette liste (nom latin en italique, et légèrement plus petit), mais ça me semble plus compliqué à gérer...

Bref, je me penche sur la question, mais si vous avez des conseils, voire un avis contraire, n'hésitez pas à réagit !

Voici une petite suggestion, dans un monde idéal ou il suffisait de claquer des doigts :yum: 

![recherche_busard_proposition](https://user-images.githubusercontent.com/26482054/47780022-cfbced00-dcfa-11e8-80d1-07ad1de1a53f.png)
(synonymes en grisé)

En attendant vos avis, je vais essayer de claquer des doigts moi même !

**Comment by TheoLechemia** [comment]
Salut Sylvain,

On voulait revenir sur le moteur de recherche des taxons dans l'atlas dans une prochaine session de dev. On a pas mal bosser dessus dans GeoNature et l'idée était de repartir sur ce qui a déjà été fait. (Recherche en AJAX, sur le nom latin + nom français). Voir ici: 
https://github.com/PnX-SI/TaxHub/blob/master/apptax/taxonomie/routestaxref.py#L263

Il y a aussi Augustin qui a proposé une pull request sur ce sujet: 
https://github.com/PnEcrins/GeoNature-atlas/pull/158

Ce que tu propose va dans le sens de ce qu'on a prévu de faire, donc tu peux avancer et on recollera les morceaus de toutes les améliorations qui ont été apportées. N'hésite pas a faire des pull request si tu le sens, c'est beaucoup facile à réintégrer ensuite.

**Comment by sig-pnrnm** [comment]
Merci Théo pour ces précisions : je vois donc que je nous ne sommes pas les seuls à ressentir ce besoin.

De mon côté cependant, je n'aurai pas les compétences en développement pour faire ce genre d'amélioration, d'autant moins de manière générique.

Mais en attendant que les améliorations de GeoNature v2 soit intégrés dans GeoNature-Atlas, je me disais que je pourrais "tout bêtement" modifier la VM `atlas.vm_search_taxon` ?
Je vois que c'est elle qui construit le champ `nom_search`

(personnellement, je suis à l'aise en SQL, mais pas trop en AJAX ou Python !)

La modif SQL devrait répondre à l'attente de mes collègues, en attendant quelque chose de plus poussé par de vrais développeurs !

**Comment by TheoLechemia** [comment]
Ah ben si tu aime bien le SQL, tu peux regarder ça !
https://github.com/PnX-SI/TaxHub/blob/master/data/taxhubdb.sql#L683
C'est la vue sur laquelle est basée la recherche de taxon dans Taxhub (et GeoNature du coup).

**Comment by sig-pnrnm** [comment]
Et si je modifie uniquement la VM `atlas.vm_search_taxon` : 
https://github.com/PnEcrins/GeoNature-atlas/blob/ec4584c7398beb6a0a4c4c2eb28ed875c62fce69/data/atlas.sql#L191-L195

Cette bête requête ne ferait pas l'affaire ?
```
 SELECT tx.cd_nom,
    tx.cd_ref,
    COALESCE((tx.nom_vern::text || ' | '::text) || tx.lb_nom::text, tx.lb_nom::text) AS nom_search
   FROM atlas.vm_taxref tx
     JOIN atlas.vm_taxons t ON t.cd_ref = tx.cd_ref
```

**Comment by TheoLechemia** [comment]
ça marche aussi. 
La vue dans Taxhub est un peu plus poussée:
tu as 
```
"lb_nom - nom_valide"
Union
 "nom_vern - nom_valide" where nom_vern NOT NULL AND cd_nom=cd_ref
```

ça permet d'avoir toujours le nom de référence (nom_valide) en plus du "lb_nom", d'enlever tous les synonymes sur la deuxième partie de la requête, et surtout d'avoir un résultat en fonction de ce que tu as tapé:
Si tu recherche sur le nom scientifique ex: "capra ibex", tu aura ce résultat:
`Capra ibex = Capra ibex Linnaeus, 1758
`

et si tu tape "bouquetin des alpes" tu aura ce résultat:

`Bouquetins des Alpes = Capra ibex Linnaeus, 1758
`
ça augmente considérablement le nombre de ligne dans ta vue par contre. D'ou le passage en Ajax necessaire.

C'est plus ou moins le mécanisme qu'il y a sur le site de l'INPN

**Comment by sig-pnrnm** [comment]
> La vue dans Taxhub est un peu plus poussée:

En effet et beaucoup plus efficace !

Je suis juste pas fan du signe ` = `

J'aurais personnellement écrit `Bouquetins des Alpes (Capra ibex Linnaeus, 1758)`, avec le nom latin en italique. Mais c'est affaire de goût et à chacun d'adapter selon ses attentes.

Au sujet de l'italique : avant de mettre le bazare sur mon instance, je préfère ton avis.
Si je mets des balises HTML dans le champ `nom_search`, seront-elle interprétées par le navigateur ?

En l'occurence, je voudrais écrire : 
`Nom français <i>(Nom latin)</i>`

```sql
COALESCE((tx.nom_vern::text || ' (<i>'::text) || tx.lb_nom::text || '</i>)'::text, '<i>'::text || tx.lb_nom::text || '</i>'::text) AS nom_search
```
La requête fonctionne bien dans PgAdmin, mais pas sûr que le résultat sera mis en forme dans la liste déroulante !
![taxons](https://user-images.githubusercontent.com/26482054/47786237-70b3a400-dd0b-11e8-92e4-d81aacc81656.png)

**Comment by sig-pnrnm** [comment]
Bon, je viens de tenter quand même, ça ne passe pas : 
![recherche_busard_pnrnm_i](https://user-images.githubusercontent.com/26482054/47786644-b2911a00-dd0c-11e8-8246-bfb0127747ef.png)

**Comment by sig-pnrnm** [comment]
A priori, c'est possible, mais là, il faut vraiment mettre la main dans le code : 
https://stackoverflow.com/questions/7292462/how-to-format-jqueryui-autocomplete-response

Si ça ne fait pas perdre de performance à la liste déroulante, ça serait intéressant je pense.
Mais là, je vous laisse chercher ;)
(je vais me contenter de `Nom français (Nom latin)` pour l'instant !

**Comment by sig-pnrnm** [comment]
Pour info, voici ce que j'ai mis pour l'instant comme requête, et le résultat, pour ceux que ça intéresse : 
```sql
COALESCE((tx.nom_vern::text || ' ('::text) || tx.lb_nom::text || ')'::text, tx.lb_nom::text) AS nom_search
```
![recherche_busard_pnrnm_ok](https://user-images.githubusercontent.com/26482054/47788901-5d0c3b80-dd13-11e8-82af-b5fec7ce46f7.png)

**Comment by sig-pnrnm** [comment]
Et pour distinguer les synonymes des noms de références, je viens d'ajouter un petit texte...
Ce serait beaucoup mieux avec une mise en forme HTML (grisé par exemple), mais en attendant, ça permet d'expliquer pourquoi on voit 2 Busards Saint-Martins : 

```sql
COALESCE((tx.nom_vern::text || ' ('::text) || tx.lb_nom::text || ')'::text, tx.lb_nom::text) || CASE WHEN t.cd_ref <> tx.cd_nom THEN ' [Syn.]'::text ELSE ''::text END  AS nom_search
```

![recherche_busard_pnrnm_ok2](https://user-images.githubusercontent.com/26482054/47789457-da847b80-dd14-11e8-9806-b6c18d1f4ec2.png)

**Comment by camillemonchicourt** [comment]
Oui on avait déjà tenté la mise en forme HTML, l'italique etc...
On reprendra le fonctionnement de GeoNature prochainement.
