### ISSUE TITLE
Problème de performances pour le rafraichissement de la vm_observation_mailles

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature-atlas#173]
Bonjour, 

J'ai là aussi un problème avec la requete `REFRESH MATERIALIZED VIEW CONCURRENTLY vm_observations_mailles` qui
prend 12h pour 550 000 données dedans. Pour comparaison le rafraichissement de la vue vm_observations prend 10 min, ce qui parait plus raisonnable. 
Est-ce qu'il y a des choses à vérifier qui pourraient expliquer cette lenteur ?

merci

**Comment by gildeluermoz** [comment]
Oui les index spatiaux (gist). Vérifie tes index spatiaux sur les geom concernés par les st_intersects (observation et mailles) Au besoin refresh les index. De grosses géométries peuvent aussi plomber les perfs. sinon simplement le fait d'avoir toute la France, ça fait beaucoup de mailles et bcp de maille X bcp de données, ça fait très très beaucoup de calcul et le processeur du serveur a son importance.
Il peut aussi y avoir des pistes d'amélioration de la conf postgres sur la taille de la mémoire allouée mais c'est pointu. Je ne maîtrise pas.

**Comment by camillemonchicourt** [comment]
C'est étonnant car on a le même volume de données. Tu es sur un territoire plus large (Occitanie) que nous mais ça devrait pas augmenter autant. Nous ça prend quelques minutes.

Le SQL : 

https://github.com/PnEcrins/GeoNature-atlas/blob/develop/data/observations_mailles.sql#L3-L11

Notre différence est qu'on est en V1, alors que tu es en V2, branché en FDW sur le ref_geo de GeoNature. Du coup c'est surement là qu'est la grosse perte de performances car la table des mailles est distante : 

https://github.com/PnEcrins/GeoNature-atlas/blob/develop/data/gn2/atlas_ref_geo.sql#L64-L71

**Comment by RomainBaghi** [comment]
Le ralentissement venait de l'utilisation d'un ST_TRANSFORM inutile dans la requete de la vue (les données sont déjà en srid 3857, et le st_transform empêche l'utilisation des index) : 
`JOIN atlas.t_mailles_territoire m ON st_intersects(obs.the_geom_point, st_transform(m.the_geom, 3857))`

Merci Mathieu B. pour la solution :)

**Comment by TheoLechemia** [comment]
Fait.
