### ISSUE TITLE
Multilingue

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-atlas#175]
Le multilingue a été mis en place par @TheMagicia dans une branche dédiée : https://github.com/PnEcrins/GeoNature-atlas/tree/multilingue

Voir les développements : https://github.com/PnEcrins/GeoNature-atlas/compare/develop...multilingue

Pour cela : 
- la librairie Flask-Babel a été ajoutée au projet
- des fichiers de langue en français et en anglais ont été mis en place (``translations/en/LC_MESSAGES/messages.po`` et ``translations/fr/LC_MESSAGES/messages.po``)
- les textes dans les templates ont été remplacés
- les pages HTML statiques ont été traduites en français et en anglais (``static/custom/templates/presentation_en.html`` et ``static/custom/templates/presentation_fr.html``)
- des paramètres ont été ajoutés au fichier de configuration pour définir les langues disponibles et la langue par défaut

En fonction de la langue du navigateur, l'application va s'afficher dans une langue ou une autre. Si il ne trouve pas de fichiers de langue correspondant à la langue du navigateur, il va utiliser la langue définie par défaut.

Seulement l'application est traduite, les contenus ne sont disponibles que dans une langue, car TaxHub ne prévoit pas de multilingue actuellement.

**Comment by gildeluermoz** [comment]
:+1:

**Comment by Adrien-Pajot** [comment]
Le lien n'est plus accessible, est-ce que tu peux en remettre un valide stp @camillemonchicourt

**Comment by Adrien-Pajot** [comment]
En tout cas j'ai créé une PR #299 pour que ce soit implémenté pour la V2

**Comment by camillemonchicourt** [comment]
Le lien de quoi ? 
D'un atlas qui fonctionne en multilingue ?
Il y a http://jamaica.geonature.fr
Pour tester, il faut paramétrer son navigateur en anglais.

**Comment by camillemonchicourt** [comment]
Le multilingue a été repris et amélioré par @corentinlange, @Adrien-Pajot et @TheoLechemia et intégré dans la version 1.5.0.

C'est toute l'interface de l'outil qui est traduit, et non pas les contenus qui viennent de la BDD qui ne sont disponibles que dans une langue.
Pour cela des fichiers de langue ont été mis en place en français, anglais et italien : https://github.com/PnX-SI/GeoNature-atlas/tree/master/atlas/translations
La méthode pour ajouter une langue ou des clés de traduction est documentée : https://github.com/PnX-SI/GeoNature-atlas/blob/master/docs/changelog.rst

Il est important désormais de s'appuyer sur ces fichiers de langue et de ne pas ajouter de texte directement dans les templates.

Le mode multilingue est désactivé par défaut, activable avec le paramètre ``MULTILINGUAL`` : https://github.com/PnX-SI/GeoNature-atlas/blob/master/atlas/configuration/config.py.example#L51

Quand le multilingue n'est pas activé, l'application va quand même s'appuyer sur un fichier de langue, en utilisant la langue définie par le paramètre ``DEFAULT_LANGUAGE`` : https://github.com/PnX-SI/GeoNature-atlas/blob/master/atlas/configuration/config.py.example#L48

Il est donc aussi possible de ne proposer l'application qu'en français, qu'en anglais, qu'en italien, ou autre si on ajouter d'autres fichiers de langue.

Quand le mode multilingue est activé : 

- Les clés de langue sont ajoutées dans les URL (ex : http://monatlas.fr/en/espece/60585)
- Si on accès à une URL sans clé de langue la page est redirigée avec la clé de langue pour que les anciennes URL sans multilingue continuent à fonctionner (pour ceux qui ont déjà l'atlas sans multilingue, le référencement et les liens)
- Pour définir la langue proposée à l'utilisateur, l'application va détecter la langue de son navigateur
- Si langue du navigateur n'est pas disponible dans les langues proposées, alors on utilise la langue par défaut (``DEFAULT_LANGUAGE``)
- Le référencement a été optimisé avec l'ajout de balises de métadonnées ``alternate`` et ``canonical``
- Des clés de traductions ont été ajoutés dans les templates de customisation. Vous pouvez les reporter si vous le souhaitez dans vos templates customisés si vous avez déjà un GeoNature-atlas installé en version inférieure à 1.5.0. Exemple dans le template https://github.com/PnX-SI/GeoNature-atlas/blob/1.5.0/atlas/static/custom/templates/introduction.html.sample#L11 correspondant à la clé https://github.com/PnX-SI/GeoNature-atlas/blob/1.5.0/atlas/translations/fr/LC_MESSAGES/messages.po#L89

**Reste quelques ajustements et compléments possibles :**

- Mise en place d'un mécanisme de surcouche des fichiers de langue, permettant à chacun d'adapter les textes
- Traduire les textes dans Leaflet car actuellement les textes dans la carte sont en dur en français.
