### ISSUE TITLE
Installation directe de geoNature Atlas 1.3.2

### ISSUE THREAD

**Issue by CistudeNature** [PnX-SI/GeoNature-atlas#176]
Bonjour,
Je suis en train d'installer directement geoNature Atlas 1.3.2 sur une plateforme où GeoNature 2.0 est opérationnel.
Lors de l'exécution du script sudo ./install_db.sh, j'ai le message d'erreur suivant 
Creation de la VM des observations de chaque taxon par mailles...
ERREUR:  la relation « atlas.vm_observations_mailles » n'existe pas
Grant...
J'ai essayé d'exécuter le script sql update_vm_observations.sql, mais cela génère d'autres erreurs.
Quels sont vos consignes pour sortir de cette impasse.
Merci d'avance pour votre retour.

**Comment by TheoLechemia** [comment]
Bonjour, 
GeoNature atlas n'est pas encore compatible avec GeoNature v2.
Des développements ont été amorcés pour assurer la compatibilité dans la branche 'develop': https://github.com/PnEcrins/GeoNature-atlas/blob/develop/install_db_gn2.sh, mais rien d'abouti ni de terminé.

**Comment by DonovanMaillard** [comment]
Bonjour, 

Je n'ai pas encore eu le temps de faire la proposition de mise à jour ici, mais pour une installation sur débian 9, il faut adapter les droits de l'utilisateur postgres pour qu'il ait accès à tout ce qu'il faut dans le ref_nomenclature, ref geo etc. Et il y a également une source à ajouter dans l'install env, au cas ou votre serveur est sur debian 9. 


Install env devient donc : 
 `
#!/bin/bash

if [ "$(id -u)" == "0" ]; then
   echo -e "\e[91m\e[1mThis script should NOT be run as root\e[0m" >&2
   exit 1
fi


sudo apt-get update
sudo apt-get -y upgrade


# Go to folder of install_env.sh
cd "$(dirname "$0")"

sudo apt-get install -y unzip
sudo apt-get install -y apache2
sudo apachectl restart

sudo apt-get install -y postgresql
sudo apt-get install -y postgresql-contrib
sudo apt-get install -y postgresql-server-dev-9.6
sudo apt install -y postgis-2.3 postgis postgresql-9.6-postgis-2.3

sudo apt-get install -y python-setuptools
sudo apt-get install -y libpq-dev python-dev

sudo apt-get install -y python python-pip
sudo apt-get install -y python-gdal
sudo apt-get install -y gdal-bin

sudo apt-get install -y python-virtualenv
sudo pip install --upgrade pip virtualenv virtualenvwrapper
sudo apt-get install -y supervisor
`

**Comment by camillemonchicourt** [comment]
Oui la compatibilité V2 est fonctionnelle mais pas encore terminée.

Voir sur le sujet : https://github.com/PnEcrins/GeoNature-atlas/issues/162

**Comment by camillemonchicourt** [comment]
Attention, ce qu'indique Donovan est dans le cas où vous installez GeoNature-atlas sur un autre serveur. Ce qui n'est pas votre cas de ce que je comprends.
