### ISSUE TITLE
Internal Server Error lors des consultations des fiches espèces

### ISSUE THREAD

**Issue by CistudeNature** [PnX-SI/GeoNature-atlas#189]
Bonjour,
Lors de la consultation des fiches espèces, nous avons
 systématiquement le message suivant "Internal Server Error".
Nous utilisons les versions suivantes :
- Geonature Atlas 1.3.3dev0
- Geonature 2.0.1 

Ci-joint la log d'Atlas [atlas.log](https://github.com/PnX-SI/GeoNature-atlas/files/3187455/atlas.log) qui indique un dépassement dans un tableau.
Merci d'avance pour votre aide.
Cistude Nature

**Comment by camillemonchicourt** [comment]
La compatibilité de GeoNature-atlas avec GeoNature 2.x n'est pas terminée. 
L'utilisation des branches ``develop`` nécessite de bien connaitre techniquement les outils. 
Mais je sais que certains ont déjà réussi à faire tourner un GeoNature-atlas sur une V2 de GeoNature.
