### ISSUE TITLE
Les images de la gallerie photos ne s'affichent pas + ...

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/GeoNature-atlas#192]
Il y a une erreur lorsqu'un média a une valeur null notamment dans l'attribut licence
![image](https://user-images.githubusercontent.com/3088650/58180502-83db9080-7caa-11e9-99be-00f7aedf2486.png)

**Comment by amandine-sahl** [comment]
Autre erreur sur la gallery : impossible d'afficher les images d'un groupe

**Comment by camillemonchicourt** [comment]
En effet dans la branche develop
