### ISSUE TITLE
Ergonomie de la recherche

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-atlas#193]
Lors des recherches, certains résultats peuvent-être très nombreux (cas des communes Saint-Etienne avec 25 communes en Auvergne-Rhône-Alpes) ce qui rend la recherche de communes difficile. cf. capture ci-après (tous les Saint-Etienne ne sont pas affichés).

![liste_commune](https://user-images.githubusercontent.com/22891423/58550988-4bd6cf00-820f-11e9-8a59-4694d596432f.jpg)

**Comment by camillemonchicourt** [comment]
Quelle idée d'avoir tous ces St-Etienne, ils ont pas d'imagination ? 😀
Faudrait pas limiter à 20 résultats du coup...

**Comment by lpojgc** [comment]
Le problème est le même (et accentué !) par la recherche de la page d'accueil, dans le bloc en quelques chiffres.
La recherche est limitée à 10 résultats, ce qui rend impossible la sélection de la commune Saint-Etienne dans la Loire.

**Comment by jbdesbas** [comment]
En triant les résultats de la requête par longueur du nom de la commune ca roule (dans la Somme on a le village de "Y"...)

**Comment by TheoLechemia** [comment]
Intégré dans cette PR: https://github.com/PnX-SI/GeoNature-atlas/pull/200
