### ISSUE TITLE
Simplification de la liste d'espèces

### ISSUE THREAD

**Issue by lpojgc** [PnX-SI/GeoNature-atlas#194]
On a plusieurs retours d'utilisateurs de https://carto.fauneauvergnerhonealpes.org/ qui sont déroutés par la présence de tous les synonymes dans le menu déroulant de recherche. Ne serait-il pas possible de ne sélectionner que les taxons valides (cdnom=cdref) pour l'alléger ?

**Comment by camillemonchicourt** [comment]
La recherche a été complètement revue pour être bien pertinente et intelligente : https://github.com/PnX-SI/GeoNature-atlas/commit/a49057109dfae0b82fb952cbcc60e569c5edd24d
Cela sera disponible dans la prochaine version.

On a toujours les synonymes (quand on cherche en latin uniquement), nécessaires si jamais une personne cherche par un synonyme. Par contre ils ont triés par pertinence et avec les noms de référence en premier.

La méthode retenue est la même que celle mise en place dans GeoNature et explicitée ici : https://si.ecrins-parcnational.com/blog/2019-01-fuzzy-search-taxons.html
Aussi testable ici : http://demo.geonature.fr/sandbox/

**Comment by lpojgc** [comment]
Parfait, merci ! Désolé de ne pas avoir suivi...

**Comment by camillemonchicourt** [comment]
Pas de soucis, tu ne pouvais pas deviner. :-)
