### ISSUE TITLE
[QUESTION] Usage de STATIC_PAGES ?

### ISSUE THREAD

**Issue by ThomasBruleOpen** [PnX-SI/GeoNature-atlas#195]
Bonjour, 

Je travaille actuellement à la mise en place de Geonature/Atlas pour le compte de Rennes Métropole. Je profite d'ailleurs de ce post pour vous féliciter pour le travail accompli sur ce projet ... L'ecosystème GN est réellement impressionnant ... Bravo !

J'ai juste une question, j'ai testé dans tous les sens, je cherche simplement à rajouter une page statique dans mon menu, par le biais du paramétrage suivant : 
`STATIC_PAGES = {
    'presentation': {'title': "Présentation de l'atlas", 'picto': 'glyphicon-question-sign', 'order': 0, 'template': 'static/custom/templates/presentation.html'}
	'partenaires': {'title': "Liste des partenaires", 'picto': 'glyphicon-question-sign', 'order': 1, 'template': 'static/custom/templates/partenaires.html'}
}`

Et je me fais jeter par une erreur de syntaxe ... Il me manque forcément un élément quelque part, mais je n'ai pas trouvé d'exemple avec 2 pages pour vérifier . Si je conserve uniquement la première page, c'est bon, c'est dès que je rajoute la deuxième page dans mon paramètre ...

Si quelqu'un pouvait m'aider ... 

Merci d'avance !

**Comment by camillemonchicourt** [comment]
Merci pour le retour 
Quelle est l'erreur qui remonte ?

**Comment by TheoLechemia** [comment]
Bonjour,
Il manque une virgule juste avant "partenaire":

```
STATIC_PAGES = { 
    'presentation':{
        'title': "Présentation de l'atlas", 
        'picto': 'glyphicon-question-sign', 
        'order': 0, 'template': 'static/custom/templates/presentation.html'
    },
    'partenaires':
     {
        'title': "Liste des partenaires", 
        'picto': 'glyphicon-question-sign', 
        'order': 1, 
        'template': 
        'static/custom/templates/partenaires.html'
    } 
}
```

**Comment by ThomasBruleOpen** [comment]
Ok, j'avais pas du tester ce séparateur .... Merci pour le support !
