### ISSUE TITLE
installation de la 1.4.0

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature-atlas#205]
j'ai une erreur dans l'exécution de l'appli : 

```
File "/home/geonatureadmin/atlas/atlas/modeles/repositories/vmObservationsMaillesRepository.py", line 77, in lastObservationsMailles    
    "group2_inpn": utils.deleteAccent(o.group2_inpn),
NameError: name 'utils' is not defined
```

 le module utils  importé : import atlas.utils au début du script n'est pas le bon.
il faut : import atlas.modeles.utils

**Comment by DonovanMaillard** [comment]
Quelques erreurs rencontrées pour ma part sur la partie BDD : 


J'ai lancé install_db.sh dans un premier temps mais je suis désormais à repasser à la main certaines choses : 

- La vm_observations_mailles ne s'est pas générée, car l'une de mes données (point) intersecte 2 mailles. Dans la VM, pas de soucis mais comme dans la foulée on crée l'index unique "id_observation'", ca ne passe plus car l'id_observation est renvoyé 2 fois. 

Sur cette même vue, l'index geojson maille ne se crée pas non plus, avec le message suivant : 
ERREUR:  la taille de la ligne index, 3752, dépasse le maximum, 2712, pour l'index « vm_observations_mailles_geojson_maille_idx »
HINT:  Les valeurs plus larges qu'un tiers d'une page de tampon ne peuvent pas être
indexées.
Utilisez un index sur le hachage MD5 de la valeur ou passez à l'indexation
de la recherche plein texte.

**Comment by TheoLechemia** [comment]
Corrigé, merci
