### ISSUE TITLE
erreur dans la fonction getTaxon de vmTaxrefRepository.py

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/GeoNature-atlas#207]
dès que je veux charger une fiche espèce, j'ai ce message :

```
File "/home/geonatureadmin/atlas/atlas/modeles/repositories/vmTaxrefRepository.py", line 123, in getTaxon
    return req[0]
  File "/home/geonatureadmin/atlas/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3017, in __getitem__
    return list(self[item : item + 1])[0]
IndexError: list index out of range
```

**Comment by TheoLechemia** [comment]
C'est très bizarre. ça veut dire que tu as des cd_nom qui ne sont pas Taxref, ou alors des rang qui ne correspondent à rien dans la table "bib_taxref_rang".
J'ai corrigé la requête pour ne pas prendre bêtement l'indice 0 d'une liste. L'appli ne va plus bugguer, mais il y a quand même un problème de données derrière.

**Comment by RomainBaghi** [comment]
Salut, 
Dsl j'ai trouvé le problème c'est ma base taxref qui était incomplète !
Il manquait le règne ...
