### ISSUE TITLE
Installation 1.4.0 / Config.py.example

### ISSUE THREAD

**Issue by relaire** [PnX-SI/GeoNature-atlas#208]
Bonjour,
Je viens d'installer la 1.4.0 (pas d'update, installation neuve), j'ai rencontré 3 erreur dans le _config.py_ basé sur _config.py.example_ :
- Le paramètre MIN_ZOOM ( ligne 54) me renvoi une erreur dans le fichier log + erreur 503,  j'ai commenté pour poursuivre
- Le paramètre MAX_BOUNDS (ligne 55) me renvoi une erreur dans le fichier log + erreur 503, j'ai commenté pour poursuivre
- ligne 157, il manque la majuscule à **true**.

**Comment by TheoLechemia** [comment]
Bonjour,

Désolé pour ces coquilles dans le fichier d'exemple, voilà la synthaxe:

```
MAP = {
    'LAT_LONG': [44.7952, 6.2287],
    'FIRST_MAP': {
            'url' : 'https://wxs.ign.fr/IGNKEY/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
            'attribution' : '&copy; <a href="http://www.ign.fr/">IGN</a>',
            'tileName' : 'IGN'
    },
    'SECOND_MAP' : {
            'url' :'https://wxs.ign.fr/IGNKEY/wmts?LAYER=ORTHOIMAGERY.ORTHOPHOTOS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
            'attribution' : '&copy; <a href="http://www.ign.fr/">IGN</a>',
            'tileName' : 'Ortho IGN'
    },
    'ZOOM' : 10,
    MIN_ZOOM : 6,
    MAX_BOUNDS : [[41.463,-1.876],[51.62,8.6]],
    # Pas du slider sur les annees d'observations: 1 = pas de 1 an sur le slider
    'STEP': 1,
    # Couleur et épaisseur des limites du territoire
    'BORDERS_COLOR': '#000000',
    'BORDERS_WEIGHT': 3
}
```

**Comment by relaire** [comment]
Salut Théo,
Merci pour la réponse rapide, j’ai rajouté les cotes en plus


'MIN_ZOOM' : 6,



'MAX_BOUNDS' : [[41.463,-1.876],[51.62,8.6]],





A part ces deux coquilles, installation ça fonctionne parfaitement (on avait installé la branche develop cet été).

Super boulot.

Merci




De : Théo Lechémia <notifications@github.com>
Envoyé : lundi 7 octobre 2019 16:42
À : PnX-SI/GeoNature-atlas <GeoNature-atlas@noreply.github.com>
Cc : Renaud LAIRE <r.laire@parc-livradois-forez.org>; Author <author@noreply.github.com>
Objet : Re: [PnX-SI/GeoNature-atlas] Installation 1.4.0 / Config.py.example (#208)


Bonjour,

Désolé pour ces coquilles dans le fichier d'exemple, voilà la synthaxe:

MAP = {



    'LAT_LONG': [44.7952, 6.2287],



    'FIRST_MAP': {



            'url' : 'https://wxs.ign.fr/IGNKEY/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',



            'attribution' : '&copy; <a href="http://www.ign.fr/">IGN</a>',



            'tileName' : 'IGN'



    },



    'SECOND_MAP' : {



            'url' :'https://wxs.ign.fr/IGNKEY/wmts?LAYER=ORTHOIMAGERY.ORTHOPHOTOS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',



            'attribution' : '&copy; <a href="http://www.ign.fr/">IGN</a>',



            'tileName' : 'Ortho IGN'



    },



    'ZOOM' : 10,



    MIN_ZOOM : 6,



    MAX_BOUNDS : [[41.463,-1.876],[51.62,8.6]],



    # Pas du slider sur les annees d'observations: 1 = pas de 1 an sur le slider



    'STEP': 1,



    # Couleur et épaisseur des limites du territoire



    'BORDERS_COLOR': '#000000',



    'BORDERS_WEIGHT': 3



}

**Comment by TheoLechemia** [comment]
Oui avec les quotes pardon... c'est un dictionnaire python
