### ISSUE TITLE
[occtax] Saisie du premier taxon avec une recherche de résultat interminable

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/GeoNature-atlas#212]
Je remonte un problème que nous rencontrons de temps en temps pour savoir si nous sommes les seuls ou pas.
Lors de la saisie sous OCCTAX, il arrive, parfois, que la saisie du premier taxon lance une recherche de résultat interminable. Il faut du coup rafraîchir la page et la saisie refonctionne et ensuite ça déroule.
Je ne sais pas à quoi c'est du, mais ça nous arrive de temps en temps...

**Comment by TheoLechemia** [comment]
Pas de retour concernant ce bug chez nous à ce jour.
PS: Issue à déplacer dans GeoNature !
