### ISSUE TITLE
Intégration de données

### ISSUE THREAD

**Issue by CistudeNature** [PnX-SI/GeoNature-atlas#214]
Bonjour,

Nous nous préparons à intégrer dans GeoNature-Atlas des observations d’un organisme externe où ces dernières sont référencées soit au niveau code insee soit au niveau maille `5*5`.  Aucune de ces observations sont référencées au niveau du point géométrique.

**Cas des observations au niveau maille `5*5` :**

Après vérifications tous les code5km fournis sont connus de `atlas.t_maille_5`, idem pour les codes INSEE tous connus de `atlas.vm_communes`.
J’ai adapté :
-	 la vue `vm_observations` pour prendre en compte les nouvelles observations 
-	 la vue `vm_observations_mailles` pour créer les relations entre les id_maille et les id_observation de ces nouvelles observations.

Ma question est la suivante : les données « `the_geom_point` » et « `geoson_point` » de la vue `vm_observations` ne sont pas renseignées pour ces nouvelles observations, faut-il les calculer ou pas ? 

**Cas des observations au niveau code commune :**

Ma question est la suivante : les données « `the_geom_point` » et « `geoson_point` » de la vue `vm_observations` ne sont pas renseignées pour ces nouvelles observations, faut-il les calculer ou pas  et dans l’affirmatif comment fait-on pour les calculer ?

Merci d'avance pour votre retour

Cistude Nature

**Comment by gildeluermoz** [comment]
```
UPDATE ma_table
SET the_geom_point = st_centroid(the_geom) -- voir si besoin d'une reprojection avec st_transform(geom, srid_destination)
WHERE the_geom_point IS NULL
AND --éventuellement pour ne travailler que sur les données en question
```
Pour les communes ST_PointOnSurface peut-être préférable.
Pour geojson_point

`st_asgeojson(the_geom_point)`

http://postgis.net/docs/ST_Centroid.html
https://postgis.net/docs/ST_PointOnSurface.html
https://postgis.net/docs/ST_AsGeoJSON.html

**Comment by camillemonchicourt** [comment]
Oui, actuellement GeoNature-atlas, ne se base que sur des données ponctuelles et recalcule ensuite les intersections avec les mailles. 
Du coup pour les données sous forme de polygone, il faut utiliser leur centroïde et ensuite c'est ce centroïde qui sera utilisé pour associer l'observation à une maille.

Pas très satisfaisant dans votre cas où vos données sources sont des communes ou des mailles 5*5, il faudrait utiliser la géométrie source. Mais y a pas de miracle non plus quand on utilise des données sources dégradées à la commune ou à la maille.

**Comment by CistudeNature** [comment]
Merci pour vos conseils

De : gildeluermoz <notifications@github.com>
Envoyé : lundi 25 novembre 2019 10:00
À : PnX-SI/GeoNature-atlas <GeoNature-atlas@noreply.github.com>
Cc : PENEAU, BERNARD <bernard.peneau@atos.net>; Author <author@noreply.github.com>
Objet : Re: [PnX-SI/GeoNature-atlas] Intégration de données (#214)


UPDATE ma_table



SET the_geom_point = st_centroid(the_geom) -- voir si besoin d'une reprojection avec st_transform(geom, srid_destination)



WHERE the_geom_point IS NULL



AND --éventuellement pour ne travailler que sur les données en question



Pour les communes ST_PointOnSurface peut-être préférable.
Pour geojson_point

st_asgeojson(the_geom_point)

http://postgis.net/docs/ST_Centroid.html<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fpostgis.net%2Fdocs%2FST_Centroid.html&data=02%7C01%7Cbernard.peneau%40atos.net%7Cc9e0ec926a6e46e6a54f08d77185eb52%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637102692302065069&sdata=5nAX757J0lj87%2B79koxtnaZUI5NTS2LUy3L3SBav8MA%3D&reserved=0>
https://postgis.net/docs/ST_PointOnSurface.html<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpostgis.net%2Fdocs%2FST_PointOnSurface.html&data=02%7C01%7Cbernard.peneau%40atos.net%7Cc9e0ec926a6e46e6a54f08d77185eb52%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637102692302065069&sdata=PTdmiOlXQ405rDVErglpOR9IPQNX%2BgWRuUXDUBXKrgY%3D&reserved=0>
https://postgis.net/docs/ST_AsGeoJSON.html<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpostgis.net%2Fdocs%2FST_AsGeoJSON.html&data=02%7C01%7Cbernard.peneau%40atos.net%7Cc9e0ec926a6e46e6a54f08d77185eb52%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637102692302075056&sdata=Hxb43X3%2FgF92e24R1cCYemgnZeS4OdjaPfZ8u%2BSiyYs%3D&reserved=0>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPnX-SI%2FGeoNature-atlas%2Fissues%2F214%3Femail_source%3Dnotifications%26email_token%3DALC5SX6HM7IOHXLYCGAEPBLQVOHXPA5CNFSM4JQQG6NKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFBUHKA%23issuecomment-558056360&data=02%7C01%7Cbernard.peneau%40atos.net%7Cc9e0ec926a6e46e6a54f08d77185eb52%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637102692302075056&sdata=3GX1N74eCkZUAQDX4cdCtD1hZ6U1zBAsaWFGDnmhwlI%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALC5SX6UQPJPWUYSX6LIWQTQVOHXPANCNFSM4JQQG6NA&data=02%7C01%7Cbernard.peneau%40atos.net%7Cc9e0ec926a6e46e6a54f08d77185eb52%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637102692302085058&sdata=Ee6VK5XUOxwR4z%2BGdcIMBbgjL8ZH0185Z6YnPn8tcvw%3D&reserved=0>.

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l’intention exclusive des destinataires désignés. Il contient des informations confidentielles et pouvant être protégé par le secret professionnel. Si vous recevez ce message par erreur, merci d'en avertir immédiatement l'expéditeur et de détruire le message. Toute utilisation de ce message non conforme à sa destination, toute diffusion ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de l’émetteur. L'internet ne garantissant pas l'intégrité de ce message lors de son acheminement, Atos (et ses filiales) décline(nt) toute responsabilité au titre de son contenu. Bien que ce message ait fait l’objet d’un traitement anti-virus lors de son envoi, l’émetteur ne peut garantir l’absence totale de logiciels malveillants dans son contenu et ne pourrait être tenu pour responsable des dommages engendrés par la transmission de l’un d’eux.

This message and any attachments (the "message") are intended solely for the addressee(s). It contains confidential information, that may be privileged. If you receive this message in error, please notify the sender immediately and delete the message. Any use of the message in violation of its purpose, any dissemination or disclosure, either wholly or partially is strictly prohibited, unless it has been explicitly authorized by the sender. As its integrity cannot be secured on the internet, Atos and its subsidiaries decline any liability for the content of this message. Although the sender endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted.
