### ISSUE TITLE
Doublons dans liste des espèces

### ISSUE THREAD

**Issue by CistudeNature** [PnX-SI/GeoNature-atlas#219]
Bonjour,

Sur la page d'accueil standard de l'Atlas, où s'affiche la carte avec les observations d'une période donnée, nous avons un problème au niveau de la liste des espèces, certaines occurrences sont présentent plusieurs fois. Y-a-t-il un moyen de supprimer ces doublons?
Nous avons un problème similaire au niveau des mailles. Lorsqu'on clique sur une maille pour connaître les espèces observées, on retrouve des doublons si on a observé plusieurs fois la même espèce dans cette zone. Y-a-t-il un moyen de supprimer ces doublons?

Contexte :
- Version Atlas : 1.3.3dev0
- Affichage mode maille
Merci d'avance pour vos retours.

Cistude Nature

**Comment by TheoLechemia** [comment]
Bonjour,

Oui les données de l'atlas sont basés sur des vues materialisées qui sont construites à partir de la table "gn_synthese.synthese" de GeoNature. Vous pouvez donc soit supprimer ces doublons dans cette table ou alors le gérer à de la création de la vue "atlas.vm_observations"

**Comment by camillemonchicourt** [comment]
Je ne comprends pas bien de quels doublons il s'agit ?
La même espèce est comptabilisée plusieurs fois ? On n'a jamais constaté ce problème. 

Si il y a des doublons dans vos observations, alors c'est un autre sujet et cela concerne vos données, à nettoyer à la source comme l'indique @TheoLechemia. 

Attention, si il y a un soucis, il faudrait le vérifier sur une version stable, c'est-à-dire la version 1.4.1, car on ne peut pas dépanner sur une version de développement comme vous utilisez.

**Comment by camillemonchicourt** [comment]
Pouvez-vous clarifier le problème car on ne comprends pas.
Peut-être avec une capture écran illustrant le problème ?

**Comment by CistudeNature** [comment]
[cid:image001.png@01D5B02E.25219640]

Sur cette capture, on voit bien les doublons au niveau de la maille et au niveau de la liste.
De : Camille Monchicourt <notifications@github.com>
Envoyé : mercredi 11 décembre 2019 12:13
À : PnX-SI/GeoNature-atlas <GeoNature-atlas@noreply.github.com>
Cc : PENEAU, BERNARD <bernard.peneau@atos.net>; Author <author@noreply.github.com>
Objet : Re: [PnX-SI/GeoNature-atlas] Doublons dans liste des espèces (#219)


Pouvez-vous clarifier le problème car on ne comprends pas.
Peut-être avec une capture écran illustrant le problème ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPnX-SI%2FGeoNature-atlas%2Fissues%2F219%3Femail_source%3Dnotifications%26email_token%3DALC5SXYE466WH72OQE2BMHDQYDDLBA5CNFSM4JY34VB2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGSX4SI%23issuecomment-564493897&data=02%7C01%7Cbernard.peneau%40atos.net%7Cfa05a84de3284f863db908d77e2c5ea5%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637116601336451704&sdata=ix92kQzZL9PHoewt0e%2Bf67fI%2B3WifDVSL9GiOcQthrU%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALC5SX43JTUUO3HHHWQ5FLDQYDDLBANCNFSM4JY34VBQ&data=02%7C01%7Cbernard.peneau%40atos.net%7Cfa05a84de3284f863db908d77e2c5ea5%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637116601336451704&sdata=BHSgGuyL02hKlPSE7rQiUOHfrKWM68GNFEj3lGUjRQo%3D&reserved=0>.

Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l’intention exclusive des destinataires désignés. Il contient des informations confidentielles et pouvant être protégé par le secret professionnel. Si vous recevez ce message par erreur, merci d'en avertir immédiatement l'expéditeur et de détruire le message. Toute utilisation de ce message non conforme à sa destination, toute diffusion ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse de l’émetteur. L'internet ne garantissant pas l'intégrité de ce message lors de son acheminement, Atos (et ses filiales) décline(nt) toute responsabilité au titre de son contenu. Bien que ce message ait fait l’objet d’un traitement anti-virus lors de son envoi, l’émetteur ne peut garantir l’absence totale de logiciels malveillants dans son contenu et ne pourrait être tenu pour responsable des dommages engendrés par la transmission de l’un d’eux.

This message and any attachments (the "message") are intended solely for the addressee(s). It contains confidential information, that may be privileged. If you receive this message in error, please notify the sender immediately and delete the message. Any use of the message in violation of its purpose, any dissemination or disclosure, either wholly or partially is strictly prohibited, unless it has been explicitly authorized by the sender. As its integrity cannot be secured on the internet, Atos and its subsidiaries decline any liability for the content of this message. Although the sender endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted.

**Comment by camillemonchicourt** [comment]
L'image ne fonctionne pas si vous répondez par email. 
Il faut répondre ici dans le ticket sur Github et glisser ou coller l'image directement dans la réponse.

**Comment by CistudeNature** [comment]
![Screenshot_2019-12-11 Atlas Amphibiens-Reptiles Nouvelle-Aquitaine - Cistude Nature](https://user-images.githubusercontent.com/46520671/70625144-18471980-1c22-11ea-92eb-21ec0512604f.png)
Voilà une capture qui met en évidence les doublons au niveau de la maille et de la liste

**Comment by TheoLechemia** [comment]
C'est une carte des "X" dernières observations et non un carte espèces par maille. La popup est une liste d'observation et non une liste d'espèce. Il faudrait éventuellement rajouté la date pour ce soit plus claire.

**Comment by CistudeNature** [comment]
Oui effectivement c'est des observations. Je vais installer la dernière version validée de l'atlas et rajouter la date puis je reviendrai de nouveau vers vous

**Comment by TheoLechemia** [comment]
Il faut modifier le code de l'atlas pour afficher la date... ce qu'on déconseille de faire si vous voulez bénéficier des futurs évolutions.
