### ISSUE TITLE
Problème Url pour l'accès aux fiches espèces 

### ISSUE THREAD

**Issue by CistudeNature** [PnX-SI/GeoNature-atlas#221]
Bonjour,
les url pour consulter les fiches espèces à partir des mailles présentent un défaut
https://nom_domaine/espece/XXXXX (voir pièce jointe). Il manque "/atlas". 

Dans le reste de l'appli, les url d'accès aux fiches sont correctement construites (https://nom_domaine/atlas/espece/XXXXX).

Version Geonature Atlas déployée 1.4.1 
Merci d'avance pour votre retour.

Cistude Nature

**Comment by camillemonchicourt** [comment]
Bonjour.  Je ne vois pas ce que sont les fiches espèces à partir de mailles ?
Il n'y a pas de pièce jointe à votre message ?

**Comment by CistudeNature** [comment]
Oui effectivment. Ci-dessous, la pièce jointe.
![Screenshot_2020-01-13 Atlas Amphibiens-Reptiles Nouvelle-Aquitaine - Cistude Nature](https://user-images.githubusercontent.com/46520671/72268986-1c9c9300-3623-11ea-8df2-2203a4a9cf47.png)

**Comment by camillemonchicourt** [comment]
OK il y a peut être un soucis avec la génération de cette URL depuis les tooltips de la page d'accueil

**Comment by CistudeNature** [comment]
J'ai contourné le problème en rajoutant le nom du domaine dans la variable URL_APPLICATION du fichier config.py (https://nom_domaine/atlas).

**Comment by gchauve** [comment]
Bonjour, 
J'ai également constaté le problème. Il se trouve que dans le mode d'affichage "maille", les url de renvoi vers les fiches espèces sont construites avec la même fonction que l'on se trouve sur la carte de la page "home" ou de la page "commune". Or, la première se situe sur le chemin "mon-domaine/atlas" et l'autre sur "mon-domaine/atlas/commune/id_commune". Cette différence fait que la construction du lien fonctionne bien pour la page "commune", mais renvoie vers une page inexistante à partir de la page "home".
La fonction en question dans mapGenerator.js :
```
function printEspece(tabEspece, tabCdRef) {
  stringEspece = "";
  i = 0;
  while (i < tabEspece.length) {
    stringEspece +=
      "<li> <a href='../espece/" + tabCdRef[i] + "'>" + tabEspece[i] + "</li>";

    i = i + 1;
  }
  return stringEspece;
}
```

De mon côté j'ai résolu le problème en dupliquant cette fonction et en adaptant le chemin selon que l'on se trouve sur "home" ou "commune".

**Comment by camillemonchicourt** [comment]
OK je ne sais pas trop. 
Dans notre cas, l'atlas est directement sur un domaine (https://biodiversite.ecrins-parcnational.fr) et pas dans un sous dossier. 
C'est peut-être là le soucis. 
Mais en effet il faut bien renseigner l'adresse de l'application dans le paramètre ``URL_APPLICATION``.
D'autres cas ?

**Comment by lpofredc** [comment]
Merci, je viens de corriger le pb sur la branche de mise à jour vers Bootstrap4. En remplaçant le chemin relatif par la variable `configuration.URL_APPLICATION` définie dans le fichier de configuration `config.py`. Ce qui était déjà fait par ailleurs.

```javascript
function printEspece(tabEspece, tabCdRef) {
    stringEspece = "";
    i = 0;
    while (i < tabEspece.length) {
        stringEspece +=
            "<li> <a href='"+configuration.URL_APPLICATION+"/espece/" + tabCdRef[i] + "'>" + tabEspece[i] + "</li>";

        i = i + 1;
    }
    return stringEspece;
}
```

**Comment by gchauve** [comment]
Merci pour ce correctif, je l'ai repris pour notre solution.

**Comment by jpm-cbna** [comment]
Corriger sur la branche develop avec le commit https://github.com/PnX-SI/GeoNature-atlas/commit/72d880bb9c6a53b1107cb110f2daf9a2705748c3.

**Comment by camillemonchicourt** [comment]
Intégré dans la version corrective 1.4.2
