### ISSUE TITLE
Observations doublés sur la carte par commune

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature-atlas#225]
Sur la fiche d'une commune, lorsqu'on clique sur une ligne correspondant à un taxon la carte s'actualise mais affiche le double d'observation par rapport à l'information indiquée sur la ligne.

![Screenshot_20200217_173043](https://user-images.githubusercontent.com/51449363/74673057-cafda000-51ae-11ea-9138-648545534ade.png)

**Comment by camillemonchicourt** [comment]
OK bien vu les objets doivent être renvoyés et donc affichés en double sur la carte.
