### ISSUE TITLE
Migration vers Bootstrap4 ?

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-atlas#230]
GeoNature-atlas est développé avec Bootstrap 3.3. Je me propose pour migrer GeoNature-atlas vers Bootstrap 4. Cela nécessiterait aussi de modifier la source des icônes (remplacement de Glyphicon par font-awesome?).

Des remarques? contraintes ?

Merci.

**Comment by camillemonchicourt** [comment]
Merci !

**Comment by lpofredc** [comment]
Oui ;) Je ne suis pas webdesigner mais si certains ont des propositions à faire pour améliorer l'interface de l'appli, n'hésitez pas. C'est le moment ;)

**Comment by camillemonchicourt** [comment]
Globalement c'est simple et fonctionnel, donc pas de changement particulier en tête.

- Par contre, le template par défaut de la page de présentation avait un problème avec le sommaire qui est censé avoir une position fixe (https://github.com/PnX-SI/GeoNature-atlas/issues/171)
- Voir si il y a toujours ce problème : https://github.com/PnX-SI/GeoNature-atlas/issues/72
- Et les fiches Communes étaient perfectibles aussi (carte fixe hauteur 100% tronquée selon les tailles d'écran notamment)

**Comment by lpofredc** [comment]
Ok, merci. J'en profite pour restructurer les `templates`  avec une trame principale (`core/layout.html` contenant les entêtes, les barres de navigation, le pied de page) et pour chaque page en séparant les cards dans des fichiers distincts, plus facile de s'y retrouver car les pages sont longues. Flask a également des possibilités intéressantes d'organisation des contenus avec les balises jinja `{% block monbloc %}{% endblock %}`.
cf. le travail en cours ici avec les dossiers:
* `core` (éléments partagés sur tous les templates)
* `home` (page d'accueil) > _main.html est le squelette de la page qui fait appel aux différentes briques.
* `specieSheet` (fiche espèce) > idem `home`

cf. https://github.com/lpofredc/GeoNature-atlas/tree/bootstrap4/templates

**Comment by camillemonchicourt** [comment]
Voir la PR : https://github.com/PnX-SI/GeoNature-atlas/pull/232

**Comment by lpofredc** [comment]
Nouvelle proposition  de rendu de la fiche commune, remplacement de datatables par les listes avec medias de bootstrap, egalement filtrable sur les taxons
![image](https://user-images.githubusercontent.com/22891423/78191693-d4994980-7476-11ea-9a40-ace11698881b.png)
 
![Screenshot_2020-04-02 Commune de Clermont-Ferrand cbiodiv org - Atlas - LPO Auvergne-rhône-Alpes(1)](https://user-images.githubusercontent.com/22891423/78191848-2d68e200-7477-11ea-9424-615fc0c764e6.png)

**Comment by lpofredc** [comment]
Un aperçu des modifications apportées par cette migration vers BootStrap4

https://atlas.cbiodiv.org/

**Comment by camillemonchicourt** [comment]
Merci, beaucoup de choses intéressantes.

**Comment by Splendens** [comment]
Bonjour,

Je voudrais me baser sur l'atlas en version BS4 avant de continuer à faire mes propres modifications, du coup j'ai récupéré directement l'atlas ici : https://github.com/lpofredc/GeoNature-atlas/tree/bootstrap4 et je l'utilise sur mon instance de test.

Déjà merci @lpofredc ! Les fonctionnalités pour la recherche d'autres types de territoires, les fiches communes avec les territoires associés, la visualisation des répartition des taxons sur chaque fiche de territoires… tout ça est vraiment génial !! :-)

Je commence tout juste avec cette version de l'atlas, et à chaud, j'ai 2 petites questions : 

- le block "A voir en ce moment" reste vide : je ne récupère rien dans _mostViewTaxon_. Tu as remarqué ce problème aussi ? 
- est-ce tu aurais un exemple pour le template "présentation" ? C'était vraiment confortable d'avoir un exemple prémâché jusque là. Il n'y avait plus qu'à modifier les images du carousel, changer les titres du menu et insérer son propre contenu. S'il y a moyen d'avoir un exemple, je suis preneuse !  

Merci

**Comment by camillemonchicourt** [comment]
Ouais on espère pouvoir bosser sur cette PR (https://github.com/PnX-SI/GeoNature-atlas/pull/233) un de ces 4, mais il y a beaucoup de choses mélangés dedans, pas que le passage à BS4 :-)
Concernant la page de présentation, en effet, on l'a nettoyé mais c'est à revoir, comme tu dis c'est pratique d'avoir une base à adapter. On va la remettre, c'est noté dans les commentaires de la PR : https://github.com/PnX-SI/GeoNature-atlas/pull/233#pullrequestreview-386157619

**Comment by Splendens** [comment]
Oui, c'est justement toutes les fonctionnalités (en dehors de BS4) qui m'intéressent ! 

Est-ce ça veut dire que la PR https://github.com/PnX-SI/GeoNature-atlas/pull/233#pullrequestreview-386157619 va être amenée à avoir encore d'autres commit ? 
En fait, j'aimerais bien me baser sur cette version de l'atlas (avec les fonctionnalités ajoutées par Fred) pour refaire mes PR. Mais ça m'a l'air un peu compliqué de me baser sur une branche de qqun d'autre, surtout si elle doit encore bouger !

_ps :_  Pour les _mostViewTaxon_ : c'est bon j'ai trouvé le soucis, ça vient de mes données.

**Comment by camillemonchicourt** [comment]
Oui de ce qu.on avait vu en regardant rapidement il y avait quelques éléments à reprendre, quelques trucs cassés aussi.

**Comment by Adrien-Pajot** [comment]
Dans le cadre de COBIODIV SI on va faire en sorte que les PR #232 et #233 soient étudiées et intégrées parce que beaucoup de fonctionnalités et une migration importante sont effectuées. Même si cela nécessite un gros travail de relecture avec le nombre de commits.

**Comment by camillemonchicourt** [comment]
Intégré dans la 1.5.0
