### ISSUE TITLE
Données dupliquées dans la carte des observations point d'un taxon sur une commune

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/GeoNature-atlas#239]
Les données d'espèces sur la carte sont en doubles en raison double push dans de la donnée dans la liste des observations.

**Comment by lpofredc** [comment]
Fixé dans la PR #237

**Comment by camillemonchicourt** [comment]
Même chose que https://github.com/PnX-SI/GeoNature-atlas/issues/225 ?

**Comment by lpofredc** [comment]
Ah ben oui, bien vu!
