### ISSUE TITLE
problème installation Atlas

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/GeoNature-atlas#242]
Bonjour,
Sur mon système debian 9 (sous OVH) avec geonature, taxub, usershub, j'ai des erreurs lors de la création de la base de donnée en utilisant le script d'installation install : ./install_db.sh

Il y a des erreurs du type psql:data/gn2/atlas_ref_geo.sql:24: ERREUR:  droit refusé pour le schéma ref_geo
et des erreurs de création des vues.
Je me suis inspiré du settings exemple donné mais peut être mon settings est incorrect.
En pièce jointe le settings.ini et les fichiers logs de l'install et de postgres.
Christian Bièche 
Cistude Nature

[OVH2_ATLAS.zip](https://github.com/PnX-SI/GeoNature-atlas/files/4965744/OVH2_ATLAS.zip)

**Comment by camillemonchicourt** [comment]
Duplicate https://github.com/PnX-SI/GeoNature-atlas/issues/243
