### ISSUE TITLE
Problème installation GeoNature-atlas

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/GeoNature-atlas#243]
Bonjour,
Sur mon système debian 9 (sous OVH) avec geonature, taxub, usershub, j'ai des erreurs lors de la création de la base de donnée en utilisant le script d'installation install : ./install_db.sh

Il y a des erreurs du type psql:data/gn2/atlas_ref_geo.sql:24: ERREUR:  droit refusé pour le schéma ref_geo
et des erreurs de création des vues.
Je me suis inspiré du settings exemple donné mais peut être mon settings est incorrect.
En pièce jointe le settings.ini et les fichiers logs de l'install et de postgres.
Christian Bièche 
Cistude Nature

[OVH2_ATLAS.zip](https://github.com/PnX-SI/GeoNature-atlas/files/4965752/OVH2_ATLAS.zip)

**Comment by camillemonchicourt** [comment]
A priori votre GeoNature-atlas et sa BDD sont sur le même serveur que GeoNature ? Car vous avez indiqué ``geonature_fdw=false``.

Ensuite vous indiquez d'utiliser les données du schéma ``ref_geo`` de GeoNature (``use_ref_geo_gn2=true``) plutôt que des shapes (ce qui est une bonne chose), mais il faut bien le préparer avec l'installation. Vérifier les mailles, la présence et le type du territoire.

Mais dans votre cas, si vos 2 BDD sont sur le même serveur, il semble y avoir un conflit entre les utilisateurs de BDD de GeoNature et GeoNature-atlas qui ont le même nom mais pas les droits qu'il faut.

**Comment by christianbieche** [comment]
Bonjour, 
Effectivement j'installe sur le même serveur.
Pour les rôles geonatatlas et geonatuser. Ils sont existants car cela fait plusieurs fois que je fais l'installation et il existe donc déjà sous potsgres. ils doivent donc avoir les bons droits puisque c'est le script qui fait la création de ces rôles.

Pour la préparation de l'installation : mailles, type de territoire ... que dois-je faire et où trouver les informations ?

**Comment by christianbieche** [comment]
bonjour,
C'est bon j'ai résolu le problème d'installation. Problème de configuration de settings.ini

Le nom owner_atlas correspond en fait au nom de l'utilisateur de connexion dans la base geonature de même le password owner_atlas_pass correspond au password de la base geonture et pas un password pour geoatlas. 

Ce n'est pas clair dans le fichier de configuration.
LA création de la base est OK maintenant

**Comment by camillemonchicourt** [comment]
Oui, on a du mal à clarifier cette partie.
Super si c'est réglé.
