### ISSUE TITLE
Génération de la vue matérialisée "t_layer_territoire"

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoNature-atlas#256]
Bonjour,

A l'heure actuelle, la VM "t_layer_territoire" est générée par le code suivant lorsqu'on s'appuie sur une base de donnée GeoNature : 
```console
CREATE MATERIALIZED VIEW atlas.t_layer_territoire AS
WITH d AS (
	SELECT st_union(geom) , b.type_name
	FROM ref_geo.l_areas l
	JOIN ref_geo.bib_areas_types b USING(id_type)
	WHERE REPLACE(b.type_code, ' ', '_') = :type_territoire
	GROUP BY b.type_name
)
SELECT
 1::int as gid,
 type_name as nom,
 st_area(st_union)/10000 as surf_ha,
 st_area(st_union)/1000000 as surf_km2,
 ST_Perimeter(st_union)/1000 as perim_km,
 st_transform(st_union, 3857) as  the_geom
FROM d;
```

Le problème de ce code est qu'il prend en compte toutes les communes qui sont présentes dans la table 'l_areas'. Dans notre structure, nous avons dans cette table les communes de trois départements car notre PNR se situe à cheval sur trois départements. Du coup, la limite affichée dans l'atlas correspond à ces trois départements et non à celle de notre PNR.

Nous pourrions conserver dans cette table "l_areas" uniquement les communes de notre PNR, mais cela n'est pas souhaitable car nous avons quelques observations qui ont été réalisées en dehors des limites de notre PNR (environ 200).

Du coup, pour la création des limites d'un territoire (VM 't_layer_territoire') à partir de communes, il serait intéressant de rajouter une clause WHERE supplémentaire ne sélectionnant que les communes dans la table "ref_geo.l_areas" ayant dans la colonne "enable" la valeur "true" (qui correspondent uniquement aux communes de notre territoire). Voire, plus radical (en supposant que cela soit possible), créer la VM "t_layer_territoire" en se basant sur la VM "l_communes", qui elle utilise la valeur "enable" dont je parlais plus haut.

Qu'en penses les développeurs ? Y aurait-il des problèmes à cela ?

**Comment by camillemonchicourt** [comment]
Oui en effet c'est surement un oubli de notre côté.
La version 1.4.0 était une première étape vers la compatibilité de GN-atlas avec GN2, mais il y a pas de choses améliorables.

L'application est basée volontairement sur des vues matérialisées, justement pour que chacun puisse les adapter à son contexte sans devoir modifier le code source de GN-atlas.

Mais ce que tu évoques sembles une évolution qui serait pertinente pour tous, de prendre en compte le champs ``enable``.

**Comment by TheoLechemia** [comment]
Bonjour,

En faite dans le paramètre `type_territoire`, il faut mettre le type de zonage qui correspond à l'étendu de votre territoire (table `ref_geo.bib_area_type`). Donc dans votre cas la limite de votre PNR.  Il faut au préalable avoir créé ce type et insérer ce zonage dans la table `ref_geo.l_areas`.
Je ne sais pas ce que vous avez mis dans ce paramètre. Mais ce n'est pas fait pour être découpé à partir des communes initialement.

**Comment by geobrun** [comment]
C'est ce que j'ai fait au début, mais je me suis aperçu que le zonage de notre PNR n'existait pas dans la table `ref_geo.l_areas`... C'est pour ça que j'ai utilisé le paramètre des communes. Du coup, il vaut mieux effectivement que je fasse ce que n'ont pas fait mes prédécesseurs : insérer notre couche PNR dans la base. Je vais tester ça !

**Comment by camillemonchicourt** [comment]
Ah oui en effet, j'avais pas bien compris le contexte.
Si on base GN-atlas sur le ``ref_geo``, alors il faut ajouté la limite du territoire dans celui-ci avec un ``area_type`` dédié.

**Comment by geobrun** [comment]
Ok, donc c'est ce que j'ai fait : j'ai rajouté les limites de notre PNR dans la table `l_areas` de Geonature.

Par contre, impossible de modifier le code SQL servant à générer la vue matérialisée `atlas.t_layer_territoire` car cela générait une erreur disant que d'autres vues matérialisées dépendaient d'elle. Le code SQL de cette vue précisait en dur que c'était le type "COM" qui devait être utilisé pour générer les limites géographiques de notre territoire (conformément à ce que j'avais rentré dans le fichier de configuration de la base de données).

Du coup, j'ai supprimé la base de données de l'atlas et j'en ai recréé une autre en précisant que c'était le type "PNR" que je souhaitais utiliser pour les limites de mon territoire. Et bien sûr, ça a marché !

Je ferme le sujet, je ne suis pas sûr qu'il y ait une amélioration à faire. Mes prédécesseurs n'avaient juste pas rentré les limites de notre PNR : s'ils l'avaient fait, comme dans une première installation de la BDD j'avais précisé le type "PNR", cela aurait marché du premier coup... :/

**Comment by camillemonchicourt** [comment]
OK merci pour ce retour.
C'était donc une adaptation locale.
Cependant cette partie mérite clarification dans la documentation.

Pour les tables et les vues, elles sont beaucoup liées entre elles, donc si on en modifie une, il faut souvent en supprimer d'autres avant, puis les recréer dans l'ordre. 
Le plus simple est finalement d'adapter les fichiers SQL de création des tables et vues matérialisées du schéma ``atlas`` (par exemple https://github.com/PnX-SI/GeoNature-atlas/blob/master/data/gn2/atlas_ref_geo.sql#L81 ou https://github.com/PnX-SI/GeoNature-atlas/blob/master/data/atlas.sql#L20) et de relancer une installation de la BDD (``install_db.sh``).
