### ISSUE TITLE
Compatibilité avec GeoNature 2.5.2

### ISSUE THREAD

**Issue by mgageo** [PnX-SI/GeoNature-atlas#259]
Bonjour à tous,
Sur une installation fraiche debian 10.6.0, geonature 2.5.2, j'essaye d'installer la version atlas 1.4.1 en suivant https://github.com/PnX-SI/GeoNature-atlas/blob/master/docs/installation.rst
Après le paragraphe 5, j'ai une erreur
geonatureadmin@geonature252:~/atlas$   tail /home/geonatureadmin/atlas/log/errors_atlas.log
+ tail /home/geonatureadmin/atlas/log/errors_atlas.log
    ret = fn(self, con, *args, **kw)
  File "/home/geonatureadmin/atlas/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2790, in get_columns
    connection, table_name, schema, info_cache=kw.get("info_cache")
  File "<string>", line 2, in get_table_oid
  File "/home/geonatureadmin/atlas/venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 56, in cache
    ret = fn(self, con, *args, **kw)
  File "/home/geonatureadmin/atlas/venv/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2704, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: vm_observations
[2020-11-02 16:47:41 +0100] [3923] [INFO] Worker exiting (pid: 3923)
geonatureadmin@geonature252:~/atlas$

Ces deux versions sont compatibles ?
Bonne journée
Marc

**Comment by Splendens** [comment]
Bonjour, 
_A priori_ oui, c'est 2 versions sont compatibles. Je les ai installé ensemble il y a quelques jours.

Votre utilisateur de la bd atlas a bien les droits de lecture sur les tables nécessaires dans la bd de GeoNature ? (des droits insuffisants lors de la création de la bd de l'atlas pourraient expliquer pourquoi la vm_observations n'existe pas...).

**Comment by camillemonchicourt** [comment]
Oui il faudrait surtout les logs d'installation de la BDD :

_Vous pouvez consulter le log de cette installation de la base dans log/install_db.log et vérifier qu'aucune erreur n'est intervenue._

**Comment by mgageo** [comment]
Lors de l'ajout des droits postgres, j'avais eu des erreurs:
root@geonature252:~# sudo su - postgres
postgres@geonature252:~$ psql
psql (11.9 (Debian 11.9-0+deb10u1))
Saisissez « help » pour l'aide.

postgres=# CREATE USER geonatatlas WITH ENCRYPTED PASSWORD 'monpassachanger';
postgres=# GRANT USAGE ON SCHEMA gn_synthese, ref_geo, ref_nomenclatures, taxonomie TO geonatatlas;
ERREUR:  le schéma « gn_synthese » n'existe pas
postgres=# GRANT SELECT ON ALL TABLES IN SCHEMA gn_synthese, ref_geo, ref_nomenclatures, taxonomie TO geonatatlas;
ERREUR:  le schéma « gn_synthese » n'existe pas
postgres=#

j'ai modifié en "psql -d geonature2db"

**Comment by mgageo** [comment]
Dans le fichier log/install_db.log il y a effectivement des messages d'erreur avec "droit refusé" 
[install-db.log](https://github.com/PnX-SI/GeoNature-atlas/files/5480101/install-db.log)
Les droits semblent corrects
SELECT grantee, table_catalog, table_schema, table_name, privilege_type
FROM   information_schema.table_privileges
WHERE  grantee in ('geonatatlas');
   grantee   | table_catalog |   table_schema    |              table_name              | privilege_type
-------------+---------------+-------------------+--------------------------------------+----------------
 geonatatlas | geonature2db  | taxonomie         | taxref_protection_articles           | SELECT
 geonatatlas | geonature2db  | taxonomie         | taxref_changes                       | SELECT
 geonatatlas | geonature2db  | taxonomie         | taxhub_admin_log                     | SELECT
 geonatatlas | geonature2db  | taxonomie         | bib_taxref_habitats                  | SELECT
 geonatatlas | geonature2db  | taxonomie         | cor_taxon_attribut                   | SELECT
 geonatatlas | geonature2db  | taxonomie         | bib_listes                           | SELECT
 geonatatlas | geonature2db  | taxonomie         | cor_nom_liste                        | SELECT
 geonatatlas | geonature2db  | taxonomie         | t_medias                             | SELECT
 geonatatlas | geonature2db  | taxonomie         | taxref_protection_especes            | SELECT
 geonatatlas | geonature2db  | taxonomie         | v_taxref_all_listes                  | SELECT
 geonatatlas | geonature2db  | taxonomie         | taxref_bdc_statut_type               | SELECT
 geonatatlas | geonature2db  | taxonomie         | taxref_bdc_statut                    | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | t_nomenclatures                      | SELECT
 geonatatlas | geonature2db  | ref_geo           | li_grids                             | SELECT
 geonatatlas | geonature2db  | ref_geo           | dem_vector                           | SELECT
 geonatatlas | geonature2db  | ref_geo           | bib_areas_types                      | SELECT
 geonatatlas | geonature2db  | ref_geo           | l_areas                              | SELECT
 geonatatlas | geonature2db  | ref_geo           | li_municipalities                    | SELECT
 geonatatlas | geonature2db  | gn_synthese       | t_sources                            | SELECT
 geonatatlas | geonature2db  | gn_synthese       | cor_area_synthese                    | SELECT
 geonatatlas | geonature2db  | gn_synthese       | cor_observer_synthese                | SELECT
 geonatatlas | geonature2db  | gn_synthese       | cor_area_taxon                       | SELECT
 geonatatlas | geonature2db  | gn_synthese       | synthese                             | SELECT
 geonatatlas | geonature2db  | gn_synthese       | defaults_nomenclatures_value         | SELECT
 geonatatlas | geonature2db  | gn_synthese       | v_tree_taxons_synthese               | SELECT
 geonatatlas | geonature2db  | gn_synthese       | v_synthese_decode_nomenclatures      | SELECT
 geonatatlas | geonature2db  | gn_synthese       | v_synthese_for_web_app               | SELECT
 geonatatlas | geonature2db  | gn_synthese       | v_synthese_for_export                | SELECT
 geonatatlas | geonature2db  | gn_synthese       | v_metadata_for_export                | SELECT
 geonatatlas | geonature2db  | gn_synthese       | v_color_taxon_area                   | SELECT
 geonatatlas | geonature2db  | gn_synthese       | v_synthese_taxon_for_export_view     | SELECT
 geonatatlas | geonature2db  | ref_geo           | dem                                  | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | cor_nomenclatures_relations          | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | bib_nomenclatures_types              | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | defaults_nomenclatures_value         | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | cor_application_nomenclature         | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | cor_taxref_sensitivity               | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | cor_taxref_nomenclature              | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_stade_vie                          | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_sexe                               | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_nomenclature_taxonomie             | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_technique_obs                      | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_eta_bio                            | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_objet_denbr                        | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_type_denbr                         | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_meth_obs                           | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_statut_bio                         | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_naturalite                         | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_preuve_exist                       | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_statut_obs                         | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_statut_valid                       | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_niv_precis                         | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_resource_typ                       | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_data_typ                           | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_sampling_plan_typ                  | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_sampling_units_typ                 | SELECT
 geonatatlas | geonature2db  | ref_nomenclatures | v_meth_determin                      | SELECT
 geonatatlas | geonature2db  | taxonomie         | taxref                               | SELECT
 geonatatlas | geonature2db  | taxonomie         | taxref_protection_articles_structure | SELECT
 geonatatlas | geonature2db  | taxonomie         | taxref_liste_rouge_fr                | SELECT
 geonatatlas | geonature2db  | taxonomie         | import_taxref                        | SELECT
 geonatatlas | geonature2db  | taxonomie         | bib_attributs                        | SELECT
 geonatatlas | geonature2db  | taxonomie         | bib_themes                           | SELECT
 geonatatlas | geonature2db  | taxonomie         | bib_taxref_rangs                     | SELECT
 geonatatlas | geonature2db  | taxonomie         | bib_types_media                      | SELECT
 geonatatlas | geonature2db  | taxonomie         | bib_taxref_statuts                   | SELECT
 geonatatlas | geonature2db  | taxonomie         | bib_taxref_categories_lr             | SELECT
 geonatatlas | geonature2db  | taxonomie         | bib_noms                             | SELECT
 geonatatlas | geonature2db  | taxonomie         | vm_taxref_hierarchie                 | SELECT
 geonatatlas | geonature2db  | taxonomie         | v_taxref_hierarchie_bibtaxons        | SELECT
(70 lignes)

**Comment by camillemonchicourt** [comment]
Oui il y a plein d'erreurs dans les logs d'installation de la BDD. 
Vous n'avez pas du renseigner le fichier settings.ini comme il faut. A revoir.

**Comment by mgageo** [comment]
Je viens de modifier dans le fichier pg_hba.conf l'authentification de peer à md5 pour les connexions "local" et l'installation de la base se passe bien.

**Comment by mgageo** [comment]
Dans la documentation, chapitre "Accéder à votre BDD", sur la ligne
host    all     all     MON_IP_A_REMPLACER/0        md5  #Pour donner accès à une IP
je crois qu'il faudrait remplacer /0 par /32
