### ISSUE TITLE
problème referer IGN atlas/main/configuration/config.py 

### ISSUE THREAD

**Issue by pnrnm-sig** [PnX-SI/GeoNature-atlas#262]
Bonjour,

J'ai eu un échange assez long avec l'IGN concernant un problème de clé permettant l'affichage de fonds IGN à partir de notre atlas connecté à géonature v1. L'atlas en question : https://observatoire.parc-naturel-normandie-maine.fr/atlas/ (les services WMS sont le plan et la photo aérienne)

Alors, voici le problème : du jour au lendemain, les fonds de cartes ne s'affichent plus. La clé est remplacée par "pratique" en attendant, ça fonctionne. Je contacte l'IGN : notre clé est encore active, par contre le referer n'est pas bien paramétré. Le nouveau paramétrage du referer est maintenant : `https://observatoire.parc-naturel-normandie-maine.fr/.*`
`.*` pour toutes les pages, pas que l'atlas. Mais sachant que "https://observatoire.parc-naturel-normandie-maine.fr" renvoie vers "https://www.parc-naturel-normandie-maine.fr" et que je pense que la clé en question ne sert que sur l'atlas (si ça peut jouer ?).

Quand je lance la requête en ligne de commande depuis la VM qui héberge l'atlas, pas de différence : ça marche avec "pratique", ça marche pas avec notre clé. Je ne vois pas envoyer de requête en prenant en compte le referer autrement, et l'IGN n'a pas l'air de comprendre particulièrement.

J'ai fait des recherches sur le paramétrage du referer pour géonature, j'ai trouvé https://geonature.readthedocs.io/fr/1.9.1/installation.html ; j'ai l'impression que c'est paramétré comme il faut.

Bref, aucune idée pourquoi cela ne fonctionne pas. Auriez-vous une suggestion ? Je n'ai pas testé de créer une nouvelle clé.

Cordialement,
Romain - PNR NM

**Comment by camillemonchicourt** [comment]
Je vois pas trop, tu interrogeais bien le flux IGN en HTTPS ?
Peux-tu partager la partie configuration carto de la configuration de ton GeoNature-atlas (``custom.py``) ?

**Comment by pnrnm-sig** [comment]
La requête que j'ai utilisé (à partir de celle configurée dans l'atlas) est en http :

http://wxs.ign.fr/'+IGNAPIKEY+'/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}
    
Si ça concerne le referer, c'est bien "https://" (https://observatoire.parc-naturel-normandie-maine.fr/.*)

Je n'ai pas de custom.py dans mon installation. J'ai un config.py dans /geonatureadmin/atlas/main/configuration (on est encore sur la v1 de l'atlas).

    # ClÃ© IGN si vous utilisez l'API Geoportail pour afficher les fonds cartographiques
    # Ancienne clÃ© (2017) : 'joxx1od666baa9uy6qjnnlw3'
    # clé de développement IGN : 'pratique';
    # clé actuelle IGN : 'qt6qm9fi3dt4hxgw64ihxvzz'
    IGNAPIKEY = 'pratique';

    # Configuration des cartes (centre du territoire, couches CARTE et ORTHO, Ã©chelle par dÃ©faut...)
    MAP = {
        'LAT_LONG': [48.497, -0.208],
        'FIRST_MAP': {
                "url" :'http://wxs.ign.fr/'+IGNAPIKEY+'/wmts?LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
                'attribution' : '&copy; Contributeurs <a href="http://osm.org/copyright">OpenStreetMap</a> | &copy; MapBox',
                'maxZoom' : 14, # ne marche pas ??
                'tileName' : 'OSM'
            },
            'SECOND_MAP' : {
                  "url" :'http://wxs.ign.fr/'+IGNAPIKEY+'/wmts?LAYER=ORTHOIMAGERY.ORTHOPHOTOS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}',
                  "attribution": "",
                  "tileName" : 'Ortho IGN'
                },
            'ZOOM' : 9,
            # Pas du slider sur les annees d'observations: 1 = pas de 1 an sur le slider
            'STEP': 1
    }

**Comment by pnrnm-sig** [comment]
J'ai corrigé le problème en utilisant 'https://gpp3-wxs.ign.fr/' à la place de 'http://wxs.ign.fr/'

**Comment by camillemonchicourt** [comment]
OK donc c'était bien un soucis de HTTPS.
Ton atlas est en HTTPS mais tu appelais une ressource en HTTP. Les navigateurs bloquent cela par sécurité. En regardant les messages dans la console, cela te l'indiquait certainement.

Par contre il ne faut pas remplacer ``http://wxs.ign.fr/`` par ``https://gpp3-wxs.ign.fr`` mais par ``https://wxs.ign.fr/``.

gpp3-wxs... est l'ancienne URL, voir https://geoservices.ign.fr/deleted_posts/2019-05-03-redirection-auto-oshimae.html

PS : Je me suis embrouillé avec le fichier ``custom.py``, il s'agit bien du fichier ``config.py``.

**Comment by pnrnm-sig** [comment]
Super, merci beaucoup ! J'avais un doute en effet. Je vais refaire la modif.
