### ISSUE TITLE
Erreur de rattachement de données

### ISSUE THREAD

**Issue by MathieuLagarde** [PnX-SI/GeoNature-atlas#265]
Bonjour,
Une erreur de rattachement de données m'a été signalée sur notre Atlas.
A l'origine, dans ma table gn_synthese.synthese, j'ai 3 données d'une espèce qui ont été définies comme étant sensibles, et qui sont rattachées au polygone du Finistère. En synthèse, ces données apparaissent bien avec le polygone du département (http://data.biodiversite-bretagne.fr/donnees/#/ requête sur l'espèce Circaetus gallicus (Gmelin, 1788)).
Or, dans l'Atlas, ces données s'affichent avec une maille des Côtes-d'Armor, un département voisin (http://data.biodiversite-bretagne.fr/accueil/espece/2873).
En preprod, le constat est similaire, mais cette fois-ci, l'Atlas affiche 2 mailles distinctes, et différentes de celle affichée en prod.
Avez-vous déjà rencontré ce problème ? Comment puis-je le résoudre ?
Bien cordialement.

**Comment by Splendens** [comment]
Salut Mathieu !

Pour afficher des données sur l'atlas, ça passe par des points. Donc logiquement, on s'attendrait plutôt à ce que ce soit une maille au centre du Finistère qui soit affichée sur ton atlas. 

Tu as modifié la vue vm_observation ? Tu récupères les données à afficher dans l'atlas directement de ta synthèse ? Pour cette obs en particulier, le point généré pour l'atlas est bien le centroïde du Finistère ?

**Comment by camillemonchicourt** [comment]
Oui le point d'entrée pour l'Atlas est la géométrie ponctuelle de chaque observation qui est le centroide de la géométrie pour les lignes et polygones.
Pour l'affichage en maille c'est ce point qui est intersecte avec les mailles de la taille retenue en paramètre.

C'est donc pas idéal pour les observations sous forme de grand polygone qui sont rapportées au centroide puis intersectes avec les mailles.

Une réflexion est en cours par ailleurs dans un autre ticket.

**Comment by MathieuLagarde** [comment]
Salut Marie et Camille,
Oui, je m'attendais à ce que ce soit effectivement la maille intersectant le centroïde du Finistère qui s'affiche dans l'atlas.
Je n'ai rien modifié dans mes vm. J'ai simplement effectué un REFRESH MATERIALIZED VIEW.
Les données de mon atlas sont directement récupérées de ma synthèse.
Et concernant ces observations, le point retenu dans la table synthese.synthese de geonatureatlas correspond bien au centroïde du Finistère. Mais dans la vm atlas.vm_observations, j'ai ... 3 the_geom_point différents.

**Comment by camillemonchicourt** [comment]
OK donc le comportement est bien normal, avec le fonctionnement actuel, améliorable donc.

**Comment by MathieuLagarde** [comment]
> 
> 
> OK donc le comportement est bien normal

Je ne suis pas censé visualiser dans l'atlas la maille intersectant le centroïde du polygone de la donnée ?
Et comment se fait-il que dans la vm atlas.vm_observations je me retrouve avec 3 the_geom_point différents alors que la géométrie d'origine est identique pour les 3 données ?

**Comment by camillemonchicourt** [comment]
> Je ne suis pas censé visualiser dans l'atlas la maille intersectant le centroïde du polygone de la donnée ?

Si si c'est pas idéal mais c'est justement le fonctionnement actuel.

**Comment by Splendens** [comment]
> Et concernant ces observations, le point retenu dans la table synthese.synthese de geonatureatlas correspond bien au centroïde du Finistère. Mais dans la vm atlas.vm_observations, j'ai ... 3 the_geom_point différents

Ah oui, c'est pas ce qui est attendu..! Tu peux donner le DDL de ta vm_observations ?

**Comment by MathieuLagarde** [comment]
OK. Mais dans la pratique, ce n'est justement pas ce que j'obtiens, puisqu'en prod, la maille qui s'affiche se retrouve dans le département d'à côté, et en preprod, je me retrouve carrément avec 2 mailles différentes...

**Comment by Splendens** [comment]
Suite à ce que m'a expliqué Mathieu : cela vient des données de la synthèse, l'atlas va bien ;)

`# DB de geonature`
gn_synthese.synthese :  3 géométries 
    => the_geom_4326 : polygone Finistère
    => the_geom_point : 1 point, centroide du polygone
    => the_geom_local : polygone Finistère

`# DB de geonature-atlas`
synthese.synthese : 3 géométries => idem gn_synthese.synthese
synthese.syntheseff : 3 géométries => les centroides des départements 22, 29, 56, soit le centroide du bon département, **et les centroides des 2 départements limitrophes.**
atlas.vm_observations : 3 géométries => les centroides des départements 22, 29 soit le centroide du bon département, **et le centroide d'un département limitrophe**.
atlas.vm_observations_mailles : 3 géométries => 2 mailles correspondant aux centroides de atlas.vm_observations

Peut-être quelque chose à voir avec cette discussion https://github.com/PnX-SI/GeoNature/issues/716 ?

**Comment by camillemonchicourt** [comment]
Oui il faut remonter à la manière dont sont créées ces vues matérialisées pour comprendre le résultats.

En effet certainement lié au ticket 716.
Mais celui-ci a été règle dans GeoNature 2.5.
Et il sera optimisé en performance de calcul dans la prochaine version de GeoNature.

Mathieu tu n'es pas en version 2.5 de GeoNature ?

**Comment by MathieuLagarde** [comment]
Bonjour,
Merci beaucoup pour vos réponses.
Je suis encore sur la version 2.4.1. Le problème devrait donc être résolu lorsque nous nous mettrons à jour.

**Comment by Adrien-Pajot** [comment]
Bonjour @MathieuLagarde , le problème a-t-il été résolu ? Votre réponse permettra de fermer l'issue, merci

**Comment by MathieuLagarde** [comment]
Bonjour @Adrien-Pajot ,
Oui, dans le sens ou les données ont été supprimées - momentanément - et ou GéoNature a été mis à jour.
