### ISSUE TITLE
Fonctionnement visualisation des infos sur la protection des espèces

### ISSUE THREAD

**Issue by ThomasBruleOpen** [PnX-SI/GeoNature-atlas#281]
Bonjour, 

Je souhaiterais comprendre comment fonctionne la visualisation des informations sur la protection des espèces. Sur notre atlas, j'ai une espèce (la mésange bleue) qui est protégée, or, les infos de protection n'apparaissent pas dans la fiche espèce correspondante (alors qu'elle apparait sur les atlas de régions voisines)
Lorsque je navigue dans Taxhub, les protections sont bien présentes. 
J'ai donc tenté de remonter le fil de l'information depuis le template jusqu'à la base, et il semblerait que son affichage dépende de la présence d'un champ personnalisé renseigné dont je ne dispose pas et pour lequel la valeur du champ serait renseigné (dans cor_taxon_attribut)

Faut il donc remplir quelque chose à la main malgré la présence des informations dans des tables spécifiques ?

Merci d'avance pour votre aide.

**Comment by Splendens** [comment]
Bonjour, 

Il faut activer l'affichage de la protection dans le fichier de configuration de l'atlas (paramètre  PROTECTION à TRUE), et également ajouter l'attribut "protégé" (oui ou non) dans la BD de GeoNature, dans la table taxonomie.bib_attributs , par exemple :
 
```
id_attribut : 1	
nom_attribut : atlas_protection	
label : protection	
type : text
list_valeurs : {"values":["oui","non"]}	
type_widget : select
id_theme : 3 (l'id de l'atlas)
```

**Comment by ThomasBruleOpen** [comment]
Bonjour, 

Merci beaucoup pour vos réponses, j'ai pu m'en sortir et çà fonctionne. J'avais effectivement vu passer l'issue 157, mais dont le dernier message commençait à dater :)

**Comment by ThomasBruleOpen** [comment]
> ```
> id_attribut : 1	
> nom_attribut : atlas_protection	
> label : protection	
> type : text
> list_valeurs : {"values":["oui","non"]}	
> type_widget : select
> id_theme : 3 (l'id de l'atlas)
> ```

A noter que selon moi, l'id_attribut doit être valué à 2, comme il fait référence à l'id indiqué en dur dans le script de vm_taxon : 

> SELECT DISTINCT n.cd_ref,
            pat.valeur_attribut AS patrimonial,
            pr.valeur_attribut AS protection_stricte
           FROM tx_ref n
             LEFT JOIN taxonomie.cor_taxon_attribut pat ON pat.cd_ref = n.cd_ref AND pat.id_attribut = 1
             LEFT JOIN taxonomie.cor_taxon_attribut pr ON pr.cd_ref = n.cd_ref AND **pr.id_attribut = 2**

_Ca ne marchait pas avec l'id 1_

Donc pour de futures utilisateurs s'interrogeant ....

Merci encore, en tout cas !
