### ISSUE TITLE
Mailles de 250m : comment fonctionnent les mailles ?	

### ISSUE THREAD

**Issue by ThomasBruleOpen** [PnX-SI/GeoNature-atlas#284]
Bonjour à tous, 

Je suis en train de finaliser un atlas de la biodiversité pour la ville de Rennes, qui se limitera, en tout cas dans un premier temps, au territoire communal. 

Afin d'avoir une visualisation efficace sur la carte, on me demande d'afficher des mailles de 250m. Or, les mailles, par défaut, ne descendent qu'à 1km.

Je cherche donc à comprendre comment fonctionne le maillage dans la structure Geonature/Atlas.

Or, j'ai beau creuser, j'avoue ne pas bien comprendre comment fonctionne le système de maillage ...

Après avoir consulté notamment le MCD de l'appli, je crois comprendre que tout se passe sur les tables du schéma ref_geo.

Dans la table l_areas, j'ai bien un enregistrement qui correspond à Rennes (id_area = 34822).
Dans la table li_municipalities, j'ai aussi un enregistrement qui correspond (avec le même id_area).

Jusqu'ici, on est conforme à ce que je vois dans le MCD. 

Là où çà se complique, c'est quand je commence à travailler sur la table li_grid. 
Il me semble comprendre qu'il s'agit de la liste de toutes les mailles disponibles, décrites par un système que je ne connaissais pas, basés sur un les deux coins opposés d'un carré. 
Par contre, quand je fais une recherche de toutes les mailles dans li_grid dont l'id_area est 34822, je n'ai rien ...

C'est à partir de là que je suis perdu, et que donc je ne comprend pas comment je vais pouvoir intégrer mon propre système de mailles...

Y aurait il une documentation quelque part que j'aurais loupé qui explique dans le détail comment çà fonctionne, ou même mieux comment intégrer son propre référentiel de mailles ? Ou quelqu'un qui puisse m'expliquer comme tout çà fonctionne ?

Merci par avance !

Thomas

**Comment by Splendens** [comment]
Bonjour,

Pour afficher les données dans l'atlas avec vos propres mailles, si vous utilisez le ref_geo de la BD de GeoNature, vous pouvez insérer vos mailles dans la table l_areas, puis modifier la VM  t_mailles_territoire dans la BD de l'atlas en conséquence :

```
CREATE MATERIALIZED VIEW atlas.t_mailles_territoire
TABLESPACE pg_default
AS SELECT st_transform(c.geom, 3857)::geometry(MultiPolygon,3857) AS the_geom,
    st_asgeojson(st_transform(c.geom, 4326)) AS geojson_maille,
    c.id_area AS id_maille
   FROM ref_geo.l_areas c
     JOIN ref_geo.bib_areas_types t ON t.id_type = c.id_type
  WHERE t.type_code::text = '**_MONCODEDEMAILLE_**'::text
```

Ensuite, il faudra recalculer/recréer la VM atlas.vm_observations_mailles.

**Comment by ThomasBruleOpen** [comment]
Ah oui !!! En fait, je n'avais pas vu qu'il y avait aussi les mailles dans l_areas ... 

Mais donc par contre, quel est l'intérêt de la table l_grid ? Dois je l'alimenter aussi ?

**Comment by camillemonchicourt** [comment]
li_grid (comme li_municipalities) sont 2 tables de compléments d'info de certains objets de la table l_areas.

l_areas stocke tous les zones, et ces 2 tables permettent d'ajouter quelques infos complémentaires pour les areas de type "commune" et "maille", mais elles sont complémentaires, optionnelles et peu (pas) utilisées.
