### ISSUE TITLE
Affichage par organisme - Fiche organisme 

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/GeoNature-atlas#291]
Dans le cadre de la mission COBIODIV SI et de la problématique de traçabilité des données, afficher un dashboard par organisme (carte + données) pourrait être un ajout intéressant. Afin de fermer ce ticket : 

- [x] Mise en place de la page organisme (onglet + structuration dans la base) 
- [x] Dashboard organisme (nb d'observations, nb de taxons, nb d'observateurs ?) 
- [ ] Carte organisme
- [x] Info organisme

Cela a notamment était discuté dans l'issue #96 
Et une partie de valorisation des partenaires sur la page d'accueil est traité dans la PR https://github.com/PnX-SI/GeoNature-atlas/pull/245

**Comment by Adrien-Pajot** [comment]
En lien aussi avec #157

**Comment by camillemonchicourt** [comment]
Oui sur la page d'accueil, il faudrait indiquer l'origine des données par organisme.
Et aussi sur chaque fiche espèce, indiquer la provenance des données, en terme d'organismes.

**Comment by Adrien-Pajot** [comment]
> Oui sur la page d'accueil, il faudrait indiquer l'origine des données par organisme.

Une PR bandeau partenaire est déjà prête pour ça, si c'est bien de quoi tu veux parler ?

**Comment by Adrien-Pajot** [comment]
> Et aussi sur chaque fiche espèce, indiquer la provenance des données, en terme d'organismes.

Ticket #315

**Comment by Adrien-Pajot** [comment]
Bonjour, 
Grâce à un beau travail de @corentinlange et Mathilde Leclerc, la fiche organisme voit le jour. 
Et elle ressemble à ceci : 

<img width="1440" alt="Capture d’écran 2021-08-05 à 15 27 52" src="https://user-images.githubusercontent.com/62794251/128357879-3cd7f3d3-f8ed-4ffa-9b09-3b7460b43f3c.png">

Merci de nous faire des retours si besoin. 

Pour l'instant nous hésitons à mettre la carte des observations pour les organismes. (A l'origine nous souhaitions mettre les 100 dernières observations pour un organisme.)
Cependant, cette carte ne (me) parait pas apporter des informations suffisamment intéressantes pour les afficher.
Il pourrait être plus intéressant, comme l'a suggéré Richard Bonet, de récupérer des informations sur la structuration des métadonnées pour montrer la source des données (données aléatoires, protocolées, etc. en fonction du CA ou du JDD) ?
