### ISSUE TITLE
Ajouter l'échelle à la carte

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature-atlas#293]
Le PNR de Brière nous a demandé de rajouter l'échelle sur la carte. C'est possible facilement avec Leaflet.
Comme ceci:

![image](https://user-images.githubusercontent.com/85738261/123628302-392a8c00-d813-11eb-84aa-d957fab02d30.png)

Je fais une PR de ce pas pour ajouter ça dans la config si ça vous convient.

**Comment by camillemonchicourt** [comment]
OK très bien.
Idéalement en le mettant plutôt sous le switcher de fond.
Ou sinon à droite avec les crédits de la carte ?

**Comment by camillemonchicourt** [comment]
OK super, c'est bien comme ça.
Pas besoin de paramètre pour la position, OK pour moi.

**Comment by camillemonchicourt** [comment]
Intégré dans la 1.5.0
