### ISSUE TITLE
bug mot de passe caractères spéciaux atlas/configuration/config.py

### ISSUE THREAD

**Issue by pnrnm-sig** [PnX-SI/GeoNature-atlas#343]
Bonjour !

Je crois qu'il y a un bug dans la configuration de la connexion à la base de données au moment de l'installation de l'application avec ./install_app.sh lorsqu'on utilise un mot de passe avec certains caractères spéciaux.

Après le paramétrage de la ligne de connexion de l'application à la BDD "postgresql://user:monpassachanger@IPADRESSE:5432/databaseName" du fichier atlas/configuration/config.py j'ai rencontré les erreurs suivantes : 
- "error not running" après avoir lancé l'installation avec la commande "sudo supervisorctl restart atlas"
- dans /home/`whoami`/log/errors_atlas.log ça indiquait une erreur de connexion à la BDD avec les paramètres donnés

Ne comprenant pas l'origine de l'erreur, j'ai testé de modifier le mot de passe : j'ai enlever les caractères spéciaux % et = , relancé l'installation et maintenant ça fonctionne ! 

Je n'exclus pas de m'être trompé quelque part mais peut-être que ces caractères provoquent un bug (?).

Romain (PNR Normandie-Maine)

**Comment by jpm-cbna** [comment]
Effectivement, il ne faut pas que le login ou le mot de passe contiennent certains caractères spéciaux. La [doc de Postgresql](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) dit "The connection URI needs to be encoded with percent-encoding if it includes symbols with special meaning in any of its parts.".
La solution est donc de les encoder avec le même système que pour les URL en utilisant l'encodage à base de symbole %.
Vous pouvez utiliser un encodeur en ligne comme celui-ci : https://www.urlencoder.org/

**Comment by pnrnm-sig** [comment]
Ok, je comprends mieux. Ce n'est donc pas un bug à proprement parlé. Merci !
