### ISSUE TITLE
Affichage des données autre que nombre d'observation

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/GeoNature-atlas#373]
Bonjour,

Nous aurions un besoin pour afficher en plus des données sur le nombre d'observations, la mortalité des espèces.
(Dans une page à part accessible par le bandeau ou sur une nouvelle carte accessible sur un nouvel onglet ou un bouton)

Est ce que quelqu'un a fait un développement permettant de faire afficher sur type de données sur une carte dans l'atlas ?

ou de manière générale c'est comment peut-on afficher des données complémentaires par rapport à l'affichage standard ? 

Christian Bièche
Cistude Nature

**Comment by camillemonchicourt** [comment]
Hum, alors là il va falloir des précisions sur ce que vous voulez faire, quelles données, où elles sont, etc...

De base, GeoNature-atlas, s'appuie sur une vue qui va chercher des données dans la synthèse de GeoNature : https://github.com/PnX-SI/GeoNature-atlas/blob/master/data/gn2/atlas_synthese.sql#L3

On ne prend que les données de base dont on a besoin, donc le taxon, la date, la localisation, l'observateur, le JDD et l'effectif.

Ensuite c'est la vue matérialisée ``atlas.vm_observations`` qui est le point d'entrée central utilisée par l'atlas : https://github.com/PnX-SI/GeoNature-atlas/blob/master/data/atlas/2.atlas.vm_observations.sql
Elle s'appuie sur la vue indiquée précédemment. 
Donc il faut aussi répercuter les données à utiliser dans cette vue matérialisée ``atlas.vm_observations``.

Ensuite, il faut répercuter l'ajout de ces données dans les modèles et routes Python, puis les passer aux templates HTML pour les y afficher.

Tu peux bricoler ça sur ton atlas si tu le souhaites, ou sinon plutôt travailler sur une évolution générique pour que cela intègre l'outil partagé, mais à bien réfléchir pour transformer votre besoin spécifique en fonctionnalité générique.

**Comment by TheoLechemia** [comment]
On pourrait imaginer de faire comme les pages statiques dynamiques. C'est à dire importer un "blueprint" custom que chacun peut enrichir avec d'autre routes, et utiliser ces routes dans les pages statique

**Comment by christianbieche** [comment]
Oui bien sûr Camille, merci pour ces précisions.
On a déjà intégré dans notre Atlas un développement effectué pour la SHF et qui permet de faire afficher un nombre  par maille au lieu du nombre d'observations.
Cette demande, c'est en fait pour la GMHL que l'on aide à mettre en place son Atlas. Ils voudraient pouvoir en plus de l'affichage des observations faire afficher une carte avec les mortalités par espèce.
Je me demandais si quelqu'un avait déjà fait cela.

**Comment by christianbieche** [comment]
@TheoLechemia
Tu peux me donner plus d'explications. Je ne vois ce que tu veux dire par "blueprint" custom ? mais cela semble correspondre à ma demande.
Il y a déjà des exemples de pages statiques dynamiques dans l'atlas ?

**Comment by camillemonchicourt** [comment]
> On pourrait imaginer de faire comme les pages statiques dynamiques. C'est à dire importer un "blueprint" custom que chacun peut enrichir avec d'autre routes, et utiliser ces routes dans les pages statique

Oui bonne idée d'avoir une construction dynamique. Je pense qu'on peut faire un truc assez générique qui permettrait de récupérer n'importe quelle nomenclature en passant par son cd_nomenclature en paramètre, un truc du genre à creuser.

> On a déjà intégré dans notre Atlas un développement effectué pour la SHF et qui permet de faire afficher un nombre par maille au lieu du nombre d'observations.

Si vous faites des évolutions et qu'elles ne sont pas remises dans le pot commun, alors on ne peut pas dire grand chose. Dans tous les cas, nous on passe un temps considérable à faire en sorte que tous nos développements soient génériques et partagés.

> Cette demande, c'est en fait pour la GMHL que l'on aide à mettre en place son Atlas. Ils voudraient pouvoir en plus de l'affichage des observations faire afficher une carte avec les mortalités par espèce.

Personne à ma connaissance, mais ça serait intéressant de pouvoir mobiliser des infos venant des nomenclatures des observations présentes dans la Synthèse de GeoNature.

> Il y a déjà des exemples de pages statiques dynamiques dans l'atlas ?

Ce que dit @TheoLechemia c'est que pour les pages statiques, on peut en lister une ou plusieurs dans la configuration (https://github.com/PnX-SI/GeoNature-atlas/blob/master/atlas/configuration/config.py.example#L259-L263) et que leurs routes sont générées dynamiquement.

Par contre si j'ai compris, là il ne s'agit pas de créer des pages, mais bien d'enrichir les fiches espèces avec la possibilité d'afficher la mortalité de l'espèce sur la carte.
Mais sur quelles données vous appuyez-vous ? Sur la valeur de la nomenclature "Etat biologique" des occurrences de taxon ?

**Comment by christianbieche** [comment]
Je pensais plutôt à une carte spécifique autre que celle standard car je ne vois pas trop comment cela pourrait être visible dans la carte de la page d'accueil.

Pour Cistude nature ce serait effectivement "Etat biologique" de occurences de taxon  mais pour GMHL ce sont des tables spécifiques dont la lecture est faite dans la vue vm_observations.

Merci de vos avis.

**Comment by camillemonchicourt** [comment]
OK je ne vois pas ce que serait une carte spécifique ?
Une page dédiée, unique avec une carte des mortalités ? 
Mais du coup ça ne serait pas par espèce ?

Si l'approche est par espèce, alors ça serait intéressant d'avoir ça sur chaque fiche espèce. Pourquoi pas pouvoir switcher la carte entre un mode "Observation" et un mode "Mortalité".
On peut faire idem sur la carte de la page d'accueil, mais pour y faire afficher quoi ?

**Comment by TheoLechemia** [comment]
Oui j'avais compris une page dédié, à la manière des pages statiques, qui pourraient interroger des routes custom que chaque instance peut ajouter.
Il faudrait créer un fichier bluprint.py dans le dossier "custom", dans lequel chacun pourrait écrire les routes qu'il souhaite (dans la limite des données déjà présente en base - pas de changement de modèle de données). Ce blueprint serait importé dans le fichier "app.py".  Les templates "statiques" pourraient faire appel à ces routes personnalisées.

**Comment by Adrien-Pajot** [comment]
C'est assez intéressant parce que de nombreuses personnes commencent à nous demander des valorisation cartos autres que les observations d'espèces. On a par exemple les habitats mais aussi des catégories spécifiques comme les zonages ou les actions. On fait alors face à un problème de portée. Et on peut imaginer un front qui mange des nbtiles et qui serait un Viewer carto ou un webSIG plus qu'une appli métier. On peut en parler en direct par téléphone @christianbieche mais je suis pas sûr que GNAtlas doive tout faire ?

**Comment by camillemonchicourt** [comment]
Je pense que c'est intéressant que sur les fiches espèces on arrive d'abord sur la carte des observations, mais avoir la possibilité de switcher sur une représentation carto différente.
Par exemple on pourrait proposer par défaut de basculer sur un affichage par dernière observation, comme initié dans cette contribution : https://github.com/PnX-SI/GeoNature-atlas/pull/178 (déployé ici - https://clicnat.fr/espece/2504)
Ou justement de basculer de manière générique sur la cartographique d'une nomenclature, par exemple basculer sur une carte ayant une symbologie par valeur d'une nomenclature, dans ce cas "Etat biologique", mais de manière générique pour se baser sur n'importe quelle nomenclature.

Pour les zonages, là aussi on pourrait assez simplement permettre d'ajouter sur les cartes existantes des zonages présents dans le ref_geo.
Voir même avoir des approches par zonages, comme c'est le cas ici : https://atlas.cbiodiv.org/landscape / https://atlas.cbiodiv.org/search_query

**Comment by orovellotti** [comment]
Je pilote un projet de graphe de connaissance pour un agence de environnement étatique.

Il utilise le modèle DPSIR (En Français : FPEIR : Facteurs, Pressions, Etats, Impacts, Réponses) pour piloter leurs actions.

Les Etats ou changement d’états peuvent être des données issue de Geonature et représenter dans l'atlas sous forme d'indicateurs.

Représenté ici sous forme de StoryMap ESRI par les suisses
https://app2.ge.ch/tergeoportal/apps/Cascade/index.html?appid=ca8a25c245004599ae1273eaf26ca961

La question est la suivante, est ce qu'on peut pas imaginer que l'atlas soit un dashboard qui inclus des widgets qui présente des données issues de différentes sources pour raconter des histoires sur les évolutions de environnement ?

**Comment by camillemonchicourt** [comment]
Le sujet initial de ce ticket est de pouvoir représenter sur les cartes de chaque fiche espèce d'autres informations que les observations ou le nombre d'observations.
Notamment en s'appuyant sur des nomenclatures présentes dans la Synthèse de GeoNature.
Par exemple s'appuyer sur la nomenclature "Etat biologique" pour différencier les observations d'espèces vivantes ou mortes.

Je ne sais pas si c'est cela dont il s'agit @orovellotti ou si il s'agit d'ajouter une page de tableau de bord avec des graphiques plus globaux ? 
Ou alors d'utiliser des données provenant d'autres sources avec des widgets ?
Dans ce cas, il vaut mieux privilégier de faire un ticket différent, pour bien avoir un ticket par sujet.

Dans tous les cas, l'exemple de GE-EN-VIE est très intéressant et bien réalisé.

**Comment by christianbieche** [comment]
Bonjour,
Merci pour toutes ces remarques et suggestions. Finalement dans le cas du besoin exprimé par l'association GMHL pour lequel nous avons créé un portail Atlas, le besoin était plus simple. J'ai fait une page statique spécifique qui appelle une route créée pour le besoin de la démonstration avec un affichage simple sous forme de tableau dynamique.
GMHL va développer sa propre solution ou utiliser notre proposition mais en ajoutant simplement de nouveaux pages au menu des pages spécifiques.
Merci de vos réponses.
Si un solution générique existe un jour c'est bien sûr encore mieux.
Christian Bièche
Cistude Nature

**Comment by camillemonchicourt** [comment]
Merci pour ce retour.
C'est en ligne ? Je suis curieux de voir ça.

**Comment by christianbieche** [comment]
Alors le portail GMHL est en ligne mais pas encore opérationnel car il faut maintenant que le GMHL mette à jour l'ensemble de ces pages. Les données chargées sont à actualiser. 
Il y a donc un peu de travail de leur côté avant une mise en ligne officielle, mais le portail fonctionne.
Je te donne l'adresse en mp pour info.
