### ISSUE TITLE
BDD - générer la déclaration des géométries dans les vues matérialisées

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/GeoNature-atlas#38]
dans la vue public.geometry_columns le srid des geom est à zéro.

**Comment by TheoLechemia** [comment]
Ok pour toute les tables sauf pour syntheseff : `the_geom_3857` et `the_geom_2157` . Mais non utilisées dans l'atlas..

**Comment by Adrien-Pajot** [comment]
Traitée ou pas @TheoLechemia ?
