### ISSUE TITLE
Redirection fiche espèce vers nom retenu

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature-atlas#388]
Apparemment l'Atlas dans sa version 1.4.2 ou moins (je n'ai pas vérifié pour les versions 1.5.0+), au niveau des fiches espèces, ne redirige pas l'utilisateur vers la fiche du nom retenu.

Si l'on saisie directement une URL de l'Atlas avec un `cd_nom` non utilisé dans les observations, il affiche une fiche vide. Par exemple, pour [Acer campestre](https://atlas.biodiversite-auvergne-rhone-alpes.fr//espece/79734) (cd_ref = 79734), si j'utilise le cd_nom d'un synonyme, 130698 pour [Acer campestre subsp. hebecarpum (DC.) Pax, 1902](https://atlas.biodiversite-auvergne-rhone-alpes.fr/espece/130698), l'Atlas affiche une fiche vide.

Ne devrait-il pas automatiquement renvoyer l'utilisateur vers la fiche du nom retenu (79734) ?

**Comment by TheoLechemia** [comment]
Oui effectivement, il n'y a pas de redirection quand on saisit directement l'URL. Il n'y en a jamais eu d'ailleurs.
Le mécanisme actuel (qui n'est pas vraiment une redirection) ne fonctionne que par la recherche de taxon sur l'interface. Quand on cherche un synonyme on renvoie directement sur la page du cd_ref.
Ce serait bien de le faire sur la route directement !
