### ISSUE TITLE
Recharger les templates automatiquement

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/GeoNature-atlas#431]
Bonjour,

Suite à des demandes de certains clients voulant modifier les templates html notamment la présentation de leur atlas, je me suis posé la question s'il était possible que ces modifications soient prises en compte dès l'enregistrement du html.
Par défaut, il est nécessaire de redémarrer le service atlas pour que ces changements soient pris en compte. Or via le paramètre `TEMPLATES_AUTO_RELOAD` de Flask, le redémarrage ne devient alors plus nécessaire.

Je propose donc d'ajouter un paramètre dans la configuration, par défaut à False, qui activerait le paramètre précédent.

Qu'en pensez-vous ?

Merci d'avance pour vos retours.

**Comment by camillemonchicourt** [comment]
Si cela n'a pas de conséquences négatives, je dirai qu'autant l'activer pour tous, pour s'éviter un paramètre supplémentaire.

Mais il y a peut-être des raisons et intérêt à ne pas l'activer ?

**Comment by mvergez** [comment]
Si je ne dis pas de bêtises quand `TEMPLATES_AUTO_RELOAD` est activé, le template "renderisé" est chargé depuis le cache plutôt que relu : 
https://github.com/noirbizarre/jinja2/blob/b7d13f278753d057bb3765b4d4a672c351d88bf3/jinja2/environment.py#L757-L768
(`auto_reload` est mis à la valeur de `TEMPLATES_AUTO_RELOAD` par Flask). 

Donc pourrait potentiellement réduire la performance à cause de la lecture d'un ficher à chaque fois + la "renderisation". Je pense donc qu'il faut le désactiver par défaut et l'activer si besoin.
