### ISSUE TITLE
Sauts de lignes non pris en compte

### ISSUE THREAD

**Issue by AudreyEnGuyane** [PnX-SI/GeoNature-atlas#435]
Bonjour à tous,
l'affichage des textes (description...) sur le formulaire des espèces ne prend pas en compte les sauts de lignes des textes rédigés via taxhub.
J'ai également tenté de concaténer des chaines avec des chr(10) ou chr(13): même résultat.
Une idée d'où provient ce couac et surtout comment le résoudre?

**Comment by mvergez** [comment]
Bonjour,

Si j'ai bien compris ton problème, cela viendrait du fait que le texte inséré dans Taxhub est interprété comme du html. Donc pour sauter des lignes il est possible de mettre une balise `<br>` par exemple.

En espérant que cela vienne de là...

**Comment by camillemonchicourt** [comment]
Potentiellement en lien avec https://github.com/PnX-SI/GeoNature-atlas/issues/413 pour mieux gérer cela.
Et pouvoir générer du contenu plus riche au niveau de TaxHub.
