### ISSUE TITLE
Générer un sitemap

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-atlas#44]
Important pour le référencement car sinon les moteurs de recherche vont avoir du mal à indexer les différentes pages

http://flask.pocoo.org/snippets/108/ Ou un module Flask comme https://github.com/inveniosoftware/flask-sitemap?files=1 ?

**Comment by lpofredc** [comment]
WIP ici: https://github.com/lpofredc/GeoNature-atlas/commit/12266b56efcbe45199e41e10411c754a3eee5cba en "pur" flask, sans dépendances

**Comment by Adrien-Pajot** [comment]
Le commit de @lpofredc sur le dépôt PNX-SI, mélangé avec toute une PR : https://github.com/PnX-SI/GeoNature-atlas/pull/232/commits/12266b56efcbe45199e41e10411c754a3eee5cba

S'il est indépendant, autant faire une PR propre là-dessus et intégré que ce bout.

**Comment by camillemonchicourt** [comment]
Fait dans la 1.5.0.
Il pourrait être utile de le déclarer dans le fichier robots.txt
Et vous pouvez aussi le déclarer dans la Google Search Console pour accélérer une indexation par Google.
