### ISSUE TITLE
Régression sur l'affichage du nombre d'espèces sur le maillage au niveau communale

### ISSUE THREAD

**Issue by andriacap** [PnX-SI/GeoNature-atlas#445]
Bonjour ,

Après avoir fait une montée en version de l'Altas pour le Parc cotentin-bessin  , nous avons remarqué une régression sur l'affichage du nombre d'espèces observées par maille (au niveau communale) . En effet, en cliquant sur une maille il est affiché uniquement une espèce. Je vous joins ci-dessous la comparaison entre un bon affichage (pour le PNR FO)  et celui du Parc cotentin-bessin.

![affichage_maille_communale_atlas_foret_orient](https://user-images.githubusercontent.com/111564663/194533476-98839f1c-1545-4e6d-b8cd-d5548d502b51.png)

![affichage_maille_communale_parc-cotentin](https://user-images.githubusercontent.com/111564663/194533446-e4a94455-a0f1-4dca-904f-77617038d4e7.png)

Est-ce que ce problème est dû à la montée en version ? Si quelqu'un à déjà rencontré ce problème , nous sommes tout ouïe ^^.
En attendant , nous sommes en train d'investiguer sur le problème

**Comment by camillemonchicourt** [comment]
OK, en effet, il semble y avoir un soucis.
Il y a eu beaucoup de modifications et améliorations dans la version 1.5.0 avec de nombreux contributeurs et ça a été complexe d'intégrer et tester tout ça.
Il est possible qu'il y ait eu une régression à ce niveau.

Potentiellement avec cette évolution : 

> Refonte de la page commune, notamment en fixant la carte et en ne scrollant que dans la liste
