### ISSUE TITLE
Disparition lien "Fiche espèce" sur galerie photos

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/GeoNature-atlas#459]
Le lien intitulé "Fiche espèce" s'affichant en bas au centre de la photo affiché dans Lightbox n'est plus présent avec la v1.5 de GeoNature.

Il faudrait le remettre en place tout en évitant de modifier le code de la bibliothèque Lightbox. La correction proposée:
![Screenshot_20221223_150314](https://user-images.githubusercontent.com/51449363/209348390-989abb74-71f8-44ff-a170-2af13ea37df3.png)

Dans la v1.4:
![Screenshot_20221223_150058](https://user-images.githubusercontent.com/51449363/209348109-141b0fa0-905f-4387-8242-834b192e3594.png)

Dans la v1.5:
![Screenshot_20221223_150216](https://user-images.githubusercontent.com/51449363/209348245-ac3ca128-65a4-4209-8c5f-a54f19812eb5.png)

**Comment by mvergez** [comment]
Salut !
Cela avait été fait dans la galerie : https://github.com/PnX-SI/GeoNature-atlas/pull/432
Ce n'est pas le même résultat mais ça a été accepté :)
