### ISSUE TITLE
Dockerisation de GN Atlas

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/GeoNature-atlas#470]
- [x] Créer un fichier dockerfile (s'inspirer de https://github.com/PnX-SI/TaxHub/blob/master/Dockerfile ou https://github.com/PnX-SI/UsersHub/blob/master/Dockerfile)
- [x] fichier config référencé par la variable d'environnement `ATLAS_SETTINGS` 
- [x] dossier custom référencé par `ATLAS_CUSTOM_FOLDER`
- [x] dossier template référencé par `ATLAS_TEMPLATE_FOLDER`

- [x] ajout de `from_prefixed_env(ATLAS`)
  - !! implique une montée de version des requierements, attention aux effets de bord 

- [x] fichier `docker_startup.sh` et `docker_install_atlas_schema.sh`

**Comment by joelclems** [comment]
Deux point à régler:
- [ ] comment bien faire les fichiers `requierement.in` et `requirement.txt` apres la montée de version de `flask`
- [ ] valider les scripts `docker_startup.sh` et `docker_install_atlas_schema.sh`

**Comment by camillemonchicourt** [comment]
Dans la 1.6.0, un Dockerfile a été ajouté permettant de construire une image docker de l'atlas.
Une action Github est aussi lancé automatiquement pour construire et publiée une image à chaque PR dans `develop` et à chaque release.

**Comment by camillemonchicourt** [comment]
Dans la 2.0.0, le création de l'image Docker de GeoNature-atlas a été améliorée, avec une image "dev" et une "prod".
Un Docker-compose a été intégré au dépôt.
Les scripts d'installation de la BDD de GeoNature-atlas, spécifique à Docker ont été supprimés, pour s'appuyer sur ceux de l'installation classique.
