### ISSUE TITLE
Fiche espece et affichage des mailles - Optimisation

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-atlas#53]
Actuellement on se base sur `vm_observations_maille` pour cela mais du coup on renvoie autant d'objets qu'il y a d'observations. Du coup les mailles peuvent être dupliqués de nombreuses fois et cela alourdit le JSON. On pourrait renvoyer uniquement le nombre de mailles observées en se basant sur une `vm_taxons_mailles`.

Mais cela casserait le fonctionnement du slider pour filtrer les observations par année.

**Comment by gildeluermoz** [comment]
faut-il réellement casser le fonctionnement du slider pour une optimisation sur une page dont le chargement est somme toute assez rapide ?
La question est plutôt de tester sur un vieux tracassin avec une page affichant bcp de mailles.
Piste à creuser l'affichage des vecteurs en mode canvas.

**Comment by camillemonchicourt** [comment]
A voir quand on aura des jeux de données bien plus importants.

**Comment by gildeluermoz** [comment]
A creuser aussi une évolution permettant le chargement d'un fichier GEOJSON des mailles et un autre fichier JSON des données comportant pour chaque données l'id_maille. Le navigateur n'aurait plus de soucis avec un volume trop important de vecteurs car chaque maille ne serait présente qu'une fois (visible ou non, couleur selon nombre d'obs qui se trouvent dans le JSON).
Par contre il faut gérer le slider et en dynamique coté client calculer les changements pour chaque maille.

**Comment by sig-pnrnm** [comment]
Ca me semble plus logique aussi de n'afficher qu'une seule fois les mailles, mais je confirme qu'il serait dommage de perdre la fonctionnalité du "slider", qui est très apprécié chez nous !

**Comment by camillemonchicourt** [comment]
Oui !

**Comment by camillemonchicourt** [comment]
Pour le moment, un développement a été fait pour ajouter un paramètre permettant de désactiver le slider sur les fiches espèces, dans un dépôt à part : https://framagit.org/lpoaura/GeoNature-LpoAuRA/commit/3195406d9f7b56b63705657c6a406ea460f40231

Ces évolutions sont à reprendre pour les intégrer dans ce dépôt. 

**Précisions :**

L'option ``GROS_JEU_DONNES``  désactive le slider et provoque une requête différente (https://framagit.org/lpoaura/GeoNature-LpoAuRA/blob/lpoauradev/main/modeles/repositories/vmObservationsMaillesRepository.py) avec une vue matérialisée modifiée par ajout des dates (``dateobs``) et éviter ainsi la jointure qui prend trop de temps (ça réduit par 3 le temps de requête). Cette option désactive donc le slider de navigation historique des données. Ca transforme également l'affichage du panel avec onglets des communes et des observateurs en panel avec boutons et modals.

**Proposition d'ajustement :**

``GROS_JEU_DONNEES`` correspond plus à un contexte qu'à une fonctionnalité. 
Un paramètre correspond plus à une fonctionnalité. 
Idéalement j'aurai fait 2 paramètres puisque ce sont 2 fonctionnalités bien différentes, qui peuvent être intéressantes indépendamment.

J'aurai mis ça dans le bloc FICHE ESPECE : 

```
# Très gros jeu de données :
#  Désactive le slider chronologique sur les cartes pour alléger le nombre de données chargées
NO_SLIDER = True
# Modifie l'affichage des listes de communes et d'observateurs de la fiche espèce pour l'afficher dans une modale
LISTES_DANS_MODALE = True
```

**Comment by TheoLechemia** [comment]
Les mailles ne sont plus dupliquées, on charge une seule fois la géométrie de chaque maille avec le nombre d'observations par maille calculé en backend. 
Au mouvement du slider on recharge en AJAX en filtrant par année.
On gagne en performances sur le premier chargement. Les rechargement en AJAX après avoir filtrer par années sont eux aussi assez rapide.

https://github.com/PnX-SI/GeoNature-atlas/commit/8c135af1c117e211936e20bf256a699360d1f5e4
https://github.com/PnX-SI/GeoNature-atlas/commit/889662be0b95a4c65efc3da4bee1c3ebe033eb44

**Comment by Adrien-Pajot** [comment]
A fermer @TheoLechemia ?

**Comment by TheoLechemia** [comment]
Oui mais ça a généré ce bug: https://github.com/PnX-SI/GeoNature-atlas/issues/289
