### ISSUE TITLE
Support des mailles 500 m

### ISSUE THREAD

**Issue by Manonkreber** [PnX-SI/GeoNature-atlas#534]
GNAtlas pourrait supporter des mailles de 500 m de côté pour les espèces non sensibles. Il s’agirait de la taille de maille par défaut affichée dans les différents cartouches cartographiques de l'outil

**Comment by camillemonchicourt** [comment]
GN-atlas supporte déjà toutes les mailles que l'on veut.
Il suffit de les ajouter dans la table `l_areas` du référentiel géographique et d'ajouter un type de zonages correspondant dans la table ``bib_areas`.
Puis de faire référence au code de ce type de zonage dans le paramètre `type_maille` : https://github.com/PnX-SI/GeoNature-atlas/blob/master/atlas/configuration/settings.ini.sample#L79 et de mettre à jour les vues matérialisées.

Si on n'utilise pas le ref_geo de GeoNature, on peut aussi fournir un SHAPE avec les mailles souhaitées : https://github.com/PnX-SI/GeoNature-atlas/blob/master/atlas/configuration/settings.ini.sample#L110

Ce n'est pas un type de maille classique, ni fourni par le SINP, donc on ne propose ce type de mailles de base. 
Mais chacun peut mettre ce qu'il souhaite, même autre chose que des mailles carrées.

Il est aussi possible, si on souhaite diffuser des infos précises, de laisser l'atlas en mode POINTS, mais la plupart souhaitent flouter les données. 🤔

**Comment by bruhnild** [comment]
**Retours suite à la recette :**

- [x] Affichage par défaut des mailles 500 sur la page d'accueil

![image](https://github.com/user-attachments/assets/34a36983-dfd9-4410-807c-3d175532a277)

- [x] Support des mailles 500 sur toutes les pages où la cartographie est activée (accueil, espèce, commune)
