### ISSUE TITLE
Affichage d’une cartographie dans la fiche d’un territoire

### ISSUE THREAD

**Issue by Manonkreber** [PnX-SI/GeoNature-atlas#544]
- Besoin d'un support des couches ArcGIS
- Gestionnaire de couche
- Définition de couches SIG supplémentaires pour l’interface
- Support des mailles de 500 m (en respectant la contrainte de floutage liée à la sensibilité de l’espèce)

En cas d’impossibilité technique, il serait envisageable de remplacer les mailles par une carte de chaleur agglomérant les espèces par familles et de l’afficher en couche SIG.

**Comment by camillemonchicourt** [comment]
Partiellement redondant avec : 
- https://github.com/PnX-SI/GeoNature-atlas/issues/528
- https://github.com/PnX-SI/GeoNature-atlas/issues/534

Pour la sensibilité, il faut au préalable terminer https://github.com/PnX-SI/GeoNature-atlas/pull/441, discuté sur https://github.com/PnX-SI/GeoNature-atlas/issues/117 puis avec une autre proposition ici : https://github.com/PnX-SI/GeoNature-atlas/issues/390

**Comment by Manonkreber** [comment]
+ possibilité de configurer cette carto spécifique (choix des couches) de la fiche territoire dans le ficher de configuration de l'Atlas

**Comment by camillemonchicourt** [comment]
Je ne comprends pas. Il y a une carto spécifique aux fiches territoires ??
Ou alors les fonds carto restent bien définis globalement pour l'ensemble de l'outil GeoNature-atlas ?

**Comment by babastienne** [comment]
En effet selon moi ce besoin est déjà résolu via les tickets suivants : 
#528 (arcgis + gestion des couches)
#534
