### ISSUE TITLE
Fiche taxon : Compactage des informations pour gagner de la palce

### ISSUE THREAD

**Issue by Manonkreber** [PnX-SI/GeoNature-atlas#550]
La liste des espèces du taxon se compacterait, en cas de manque de place. Un icône permettrait d’accéder aux valeurs des colonnes qui n’ont plus la place de s’afficher. L’ordre de masquage serait tel que le nom scientifique et le nombre d’observations disparaîtront en dernier

![Image11](https://github.com/PnX-SI/GeoNature-atlas/assets/146355122/bbc5c0b0-d01c-45ab-bc97-3336272ad1d8)

Exemple d’affichage des données en mode déployé (en premier) et compacté (en second).

**Comment by camillemonchicourt** [comment]
En effet, à faire globalement sur toutes les listes de taxons. Redondant avec https://github.com/PnX-SI/GeoNature-atlas/issues/547
