### ISSUE TITLE
Fiche taxon : Ajout informations sur le taxon

### ISSUE THREAD

**Issue by Manonkreber** [PnX-SI/GeoNature-atlas#551]
La fiche du taxon comporterait une première section comportant les informations suivantes:
•	Noms vernaculaire et latin du taxon
•	Compteurs
          - Nombre d’observations
          - Nombre d’espèces
          - Nombre d’observateurs (qui doit pouvoir être masqué en paramétrage)

**Comment by TheoLechemia** [comment]
Bonjour,
La fiche espèce comprend déjà toutes ces informations

Les stats : 
![image](https://github.com/PnX-SI/GeoNature-atlas/assets/15265745/bc45ee92-75a6-4502-b53d-c65c58e310ef)

Nom latin / nom vern : 
![image](https://github.com/PnX-SI/GeoNature-atlas/assets/15265745/033cc443-4c78-4826-970d-be4c49b8f7b1)

Par contre pas sur de comprendre le "nombre d'espèces" ? Si c'est le nombre de sous espèce aggregé sur une fiche, c'est aussi déjà le cas : 
![image](https://github.com/PnX-SI/GeoNature-atlas/assets/15265745/d89cda5e-6b9d-4d7f-8528-4ed3a213008b)

Est-ce que l'idée était de faire une refonte ergonomique de la fiche ?

**Comment by Manonkreber** [comment]
My bad, j'ai mal lu. Je pensais qu'il y avait de nouvelles infos à ajouter !

**Comment by Manonkreber** [comment]
Il y avait bien un point non abordé, c'est le fait de pouvoir masquer le nombre d'observateur ! Cette fonctionnalité existe déjà?

**Comment by camillemonchicourt** [comment]
OK merci d'ouvrir un ticket dédié si besoin.
On peut masquer les observateurs (https://github.com/PnX-SI/GeoNature-atlas/blob/master/atlas/configuration/config.py.example#L46-L47), mais je ne sais pas si cela masque aussi le nombre d'observateurs. Je ne crois pas, mais à vérifier.
