### ISSUE TITLE
Floutage des données sans BDD GeoNature

### ISSUE THREAD

**Issue by Manonkreber** [PnX-SI/GeoNature-atlas#560]
Le floutage des données est possible en paramétrages si les données sources contiennent les infos utiles. GeoNature Atlas s'appuie sur le floutage implémenté dans GeoNature. Comment faire si la BDD à laquelle se rattache Geonature Artlas n'est pas un GeoNature ? Les données doivent être déjà floutées, ou le floutage est à réaliser ?

**Comment by TheoLechemia** [comment]
Lorsque GeoNature n'est pas connecté à un GeoNature, il est demandé à l'administrateur de construire par lui même les vue materialisé attendues (`vm_observations` `vm_observations_mailles` etc). C'est donc à l'administrateur de flouter les données qu'il souhaite dans ces VM.

**Comment by camillemonchicourt** [comment]
Le floutage est généré par GeoNature-atlas, donc il faut bien renseigner les nomenclatures de diffusion/sensibilité dans les données fournies à GeoNature-atlas. Mais pas flouter les données sensibles en amont. Il faut bien fournir à GeoNature les données précises, et GeoNature-atlas se charge de les flouter en fonction des données associées aux observations.
Mais par contre, actuellement, le floutage est implémenté de manière partielle dans GeoNature-atlas, uniquement avec un mécanisme de centroïde de l'objet de floutage. Et il s'appuie sur le champs "diffusion_level", ce qui n'est pas le mécanisme prévu par le SINP et donc pas le mécanisme qu'inclut GeoNature.
On voit ça ici : https://github.com/PnX-SI/GeoNature-atlas/blob/master/data/gn2/atlas_synthese.sql#L16-L38

Il y a eu un travail fait depuis pour aller plus loin et vraiment pouvoir flouter les données sensibles, avec les principes du SINP, référentiel de sensibilité, etc. Mais ce travail n'est pas terminé et intégré.
Il faudrait terminer ce travail pour pouvoir considérer que GeoNature-atlas floute bien les données sensibles comme il faut et selon les principes du SINP.

Tout ça est discuté et précisé en détail sur https://github.com/PnX-SI/GeoNature-atlas/issues/117
Il y a aussi des discussions et solutions périphériques comme discuté ici : https://github.com/PnX-SI/GeoNature-atlas/issues/390

**Comment by camillemonchicourt** [comment]
Enfin, ce que je dis est à étudier plus précisément car comme j'ai indiqué : 
- Le floutage est actuellement de manière partielle
- Le lien que j'ai donné renvoie vers une version de la vue `synthese.syntheseff` qui est celle utilisée quand on indique que l'on branche GN-atlas à un GeoNature. Cependant cela de la façon dont on utilise GNA sans GN : si on le branche directement à une autre BDD en adaptant les vues matérialisées ou si on garde la structure actuelle de la BDD sans modifier les vues matérialisées et que l'on importe régulièrement et manuellement les données depuis une autre source vers la table SYNTHESE de GNA.
- Et il serait bénéfique dans tous les cas, de reprendre et clarifier un peu cette partie de l'utilisation de GNA avec ou sans GN.

**Comment by juggler31** [comment]
Au vu de la PR existante au sujet du floutage et du travail a fournir afin de faire fonctionner le floutage dans Geonature-atlas nous avons décidé de  d'utiliser une BDD geonature.

**Comment by camillemonchicourt** [comment]
Oui je pense que c'est à la source de données de gérer le floutage pas à l'Atlas qui gérer cette complexité et afficher les données telles qu'on lui fournit.
