### ISSUE TITLE
Permettre d'intégrer des données partenaires dans les observations ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-atlas#7]
Géré au niveau de la vue qui renvoie les observations ? 

Impacte aussi l'application ?

**Comment by camillemonchicourt** [comment]
L'appli est conçue dans la logique de publier uniquement ses propres données. 

Si quelqu'un veut aussi intégrer les données de ses partenaires, il doit mettre à jour la condition WHERE de la vue ``vm_observations``.

**Comment by gildeluermoz** [comment]
Pour le moment on génère une vue qui renvoie uniquement les données de la structure. Si la vue doit renvoyer autre chose, l'utilisateur peut la modifier.

**Comment by camillemonchicourt** [comment]
Dans le cas où il y a des données partenaires, pouvoir afficher la structure en plus des observateurs

**Comment by camillemonchicourt** [comment]
Fais dans le fork du CEN Pays de Loire : https://github.com/Splendens/atlas_biodiv_pdl/commit/c7dc8e35227dd62424dca50deedf46a6f6ef4fc3

On discute pour voir comment les évolutions qu'ils font peuvent réintégrer le projet pour pas que les 2 projets vivent en parallèle.

**Comment by camillemonchicourt** [comment]
Les évolutions ont été proposés en PR : https://github.com/PnX-SI/TaxHub/issues/157

**Comment by camillemonchicourt** [comment]
Les évolutions ont été proposées en PR : https://github.com/PnEcrins/GeoNature-atlas/pull/157

**Comment by Adrien-Pajot** [comment]
Je pense que les sujets traités sont dans la 1.5.0 et qu'on peut fermer ce ticket @camillemonchicourt  ?

**Comment by camillemonchicourt** [comment]
Fonctionnalité intégrée dans la 1.5.0.
