### ISSUE TITLE
HOME - Ajouter liste des nouvelles especes

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoNature-atlas#85]
Par exemple les 5 dernieres especes découvertes. 
Je ne sais pas où le caser. Modale ?

**Comment by Adrien-Pajot** [comment]
Intéressant, est-ce que c'est à mettre en lien avec une mise en avant d'espèce de manière plus générique ? 
Le sujet est potentiellement différent : 

- Soit une liste généré automatiquement avec la date de première observation finalement de l'espèce et donc on aurait un affichage des nouvelles espèces faciles
- Soit une modale avec un choix des espèces à afficher et qui dans ce cas peut être rendu générique à toutes espèces d'intérêts ?

**Comment by Adrien-Pajot** [comment]
Dans une portée de connaissance et vue la facilité de réponse à un des problèmes je pense qu'on peut imaginer inclure ça dans les missions de Corentin pour COBIODIV.

**Comment by camillemonchicourt** [comment]
Je dirai que sur la Home il faut rester sur des blocs simples.
Par contre je pense depuis un moment qu'il faudrait ajouter une page de recherche d'espèces croisées (une synthèse simplifiee) qui a été initiée dans la PR boostrap mais à analyser, repenser, compléter.

**Comment by camillemonchicourt** [comment]
Intégré dans la 1.5.0, activable ou non.
