### ISSUE TITLE
Ajout d'un masque en dehors du territoire

### ISSUE THREAD

**Issue by sylvain-m** [PnX-SI/GeoNature-atlas#89]
Ma première "issue" sur GeoNature ! :)
Comme évoqué en direct avec Camille, nous aurions besoin de masquer (légèrement !) le territoire hors Parc.
Pour cela, nous avons utilisé sur d'autres développements le plugin Leaflet "Mask" (https://github.com/turban/Leaflet.Mask).
En paramètres (config), on pourrait ainsi : 
- activer ou non le masque
- choisir la couleur du masque (blanc ou noir par exemple), ainsi que son niveau de transparence.
Merci d'avance si quelqu'un peu implémenter cette fonctionnalité.
A+

Sylvain M.

**Comment by camillemonchicourt** [comment]
Bienvenue !

Bonne idée. Nous allons investiguer le fonctionnement du plugin

**Comment by gildeluermoz** [comment]
GeoNature  est actuellement développé avec Openlayers 2. Il faudra attendre la V2 qui sera probablement développée avec Leaflet.
À suivre....

**Comment by camillemonchicourt** [comment]
Gil c'est sur l'atlas la donc ça colle.

De ce que j'ai vu rapidement, il faut intégrer directement les coordonnées X et Y du polygone du masque. 

Idéalement il faudrait pouvoir utiliser un geojson comme ça on pourrait utiliser celui du territoire dont on dispose déjà. 

A creuser.

**Comment by gildeluermoz** [comment]
Oups, oui pardon !
Ben oui du coup ça colle.
À creuser.

**Comment by sylvain-m** [comment]
Je rajoute que la fonction Mask serait aussi tout à fait judicieuse pour les "fiches communes".
(en utilisant le même geojson que celui de la commune affichée)

**Comment by sylvain-m** [comment]
Pour faire avancer le sujet, voici quelques points d'attentions sur l'utilisation de ce plugin avec des GeoJson.
En effet, les exemples d'utilisation du plugin sont basés sur des GeoJson intégrés au script de la page.
Hors, dans le cas de GeoNature, les GeoJson seraient indépendant du script, et chargés directement sur les GeoJson existants (Communes, Périmètre Parc).

Pour cela, ayant été confronté au même problème sur une autre appli, la solution conseillée (mais que je ne sais pas mettre en oeuvre) est d'utiliser AJAX (voir [ce message](http://www.developpez.net/forums/d1578007/webmasters-developpement-web/javascript-ajax-typescript-dart/javascript/definition-variable-geojson-json-externe/#post8588853)).

Il y a même un plugin leaflet dédié à cela : https://github.com/calvinmetcalf/leaflet-ajax

En espérant que ça puisse aider à l'intérgration de cette fonctionnalité.

A+

Sylvain M.

**Comment by sig-pnrnm** [comment]
Découvrant les joies de du développement Leaflet + PostGis, j'ai découvert un plugin très simple qui permet de créer un masque depuis un GeoJson : [Leaflet.snogylop](https://github.com/ebrelsford/Leaflet.snogylop)

Il suffit de référencer ce script dans la page : 
`<script src="../src/leaflet.snogylop.js">`

Puis, d'ajouter le paramètre `invert: true` au chargement du GeoJson : 
```
L.geoJson(data, {
    invert: true
}).addTo(map);

```

Rien de plus simple !

Du coup, cette fonctionnalité serait très utile sur d'autres applications. Mon collègue qui gère GeoTrek est très intéressé, mais je lui ai dit qu'il vallait mieux proposer d'ajouter cela à l'application plutôt que de le bidouiller chez nous : est-ce que j'ouvre une issue spécifique sur le Github de GeoTrek ?

**Comment by camillemonchicourt** [comment]
Je trouvais le résultat du plugin Leaflet.Mask plus adapté car justement il fait vraiment un masque et pas cet effet bizarre de plugin inversé. 

Et oui tu peux ouvrir un ticket sur le Masque dans le Github de Geotrek-rando.

**Comment by sig-pnrnm** [comment]
> Je trouvais le résultat du plugin Leaflet.Mask plus adapté car justement il fait vraiment un masque et pas cet effet bizarre de polygone inversé.

Je ne comprends pas trop ce que tu entends par "cet effet bizarre de polygone inversé" ?
En fait, les 2 plugins ont exactement le même résultat côté client : ce sont juste des scripts différents qui tournent derrière.

Après, ce qui compte, c'est le style apporté au polygone "masque" / "inversé" : on peut choisir ce qu'on veut (dans le lien que je t'ai donné en privé la semaine dernière, j'ai choisi un remplissage blanc transparent, et une bordure pointillée avec ces paramètres : 
```
var stylepnrnm = {
        fillColor: 'white',
        opacity: 0.8,
        color: "#999999",  //Outline color
        weight: 2,
        dashArray: "5 5",
        fillOpacity: 0.3
};
```

Mais tout est envisageable : pas de bordure, une autre couleur, plus ou moins de transparence, ...
Côté client, que ce soit le plugin Mask, ou le plugin Leaflet.snogylop, le résultat sera le même et dépendra du style appliqué.

L'intérêt de Leaflet.snogylop, c'est qu'il est beaucoup plus simple à intégrer dans le script de la page.

**Comment by camillemonchicourt** [comment]
OK je capte mieux. 

Je te laisse faire une Pull Request qui intègre le Masque (activable / désactivable et dont le style est paramétrable). 

Merci !

**Comment by sig-pnrnm** [comment]
Je dois avouer que, si j'arrive à implémenter ce plugin sur une page autonome, je n'ai pas encore le niveau pour l'ajouter à l'ecosystème GeoNature, et faire en sorte qu'il soit activable / desactivable !

Mais bon, c'est l'occasion d'apprendre. ;)

Premier point, ajouter le script du plugin dans les dossiers de GeoNature-Atlas !
(je regarde comment ça se passe, mais je verrai peut-être ça que la semaine prochaine)

**Comment by camillemonchicourt** [comment]
Oui il faut ajouter le fichier `leaflet.snogylop.js` dans https://github.com/PnEcrins/GeoNature-atlas/tree/master/static/lib/leaflet

Ensuite il faut charger ce script dans les templates où il est utile (si AFFICHAGE_MAP = True), comme celui des clusters : https://github.com/PnEcrins/GeoNature-atlas/search?utf8=%E2%9C%93&q=leafletMarkerCluster.js&type=

Ensuite on peut partir sur l'idée que l'on utilise le fichier déjà existant `static/custom/territoire.json` et y faire référence comme c'est déjà le cas : https://github.com/PnEcrins/GeoNature-atlas/blob/master/templates/ficheCommune.html#L94

Il faut aussi ajouter les paramètres adéquats dans le bloc Cartographie du fichier https://github.com/PnEcrins/GeoNature-atlas/blob/master/main/configuration/config.py.sample

AFFICHAGE_MASQUE (true ou false)

et STYLE_MASQUE = {
        fillColor: 'white',
        opacity: 0.8,
        color: "#999999",  //Outline color
        weight: 2,
        dashArray: "5 5",
        fillOpacity: 0.3
};

Il faut ajouter ces paramètres dans les routes où ils sont utiles : https://github.com/PnEcrins/GeoNature-atlas/blob/master/main/atlasRoutes.py 

Enfin, il faut charger le masque dans les fichiers javascripts de génération des cartes (`static/mapGenerator.js` et autre ?) si AFFICHAGE_MAP = True

**Comment by sig-pnrnm** [comment]
Et pour faire toutes ces opérations dans une même "Pull Request" ?
Parceque, si par exemple pour commencer j'ajoute le fichier `leaflet.snogylop.js` dans https://github.com/PnEcrins/GeoNature-atlas/tree/master/static/lib/leaflet, comment faire en sorte (depuis Github sur le web si possible), de regrouper les actions suivantes à cette même Pull Request ?

**Comment by camillemonchicourt** [comment]
Ah oui, en effet il ne faut pas le faire sur Github. 
L'idéal est d'avoir Git installé sur un serveur de DEV où tu as el projet GeoNature-atlas. Tu ajoutes et modifies les fichiers que tu veux, tu peux ainsi tester et une fois que c'est bon, tu fais tes commandes (git add, git commit, git push...).
Sinon, plus simple, tu as Github pour Windows : https://desktop.github.com/
Tu l'installes sur ton poste, tu te connectes à ton compte Github, tu clones localement le projet que tu souhaites, tu fais les modifications en local puis tu fais une Pull request directement.

**Comment by camillemonchicourt** [comment]
Sinon directement en WEB c possible aussi d'ajouter plusieurs commits dans une seule Pull Request mais ça va te faire un commit par Fichier ajouté ou modifié donc c'est un peu lourdingue. 

Pour ça tu dois créer une branche dédiée, tu y fais tes différents commits et ensuite tu compares ta branche à la branche develop et tu crée une Pull Request. 
Tu peux même y ajouter des commits après avoir fait la Pull request en faisant d'autres commits dans cette branche.

**Comment by Jeje2201** [comment]
Bonjour @camillemonchicourt, est-ce que cette issue a évolué en 4 ans ?

Ou devons-nous toujours développer nous même cette intégration de fond différent que la zone sélectionnée pour une aide visuelle ?

Je n'ai pas vraiment trouvé de commit en rapport si ce n'est des mentions d'issues dans des mentions d'issues

**Comment by camillemonchicourt** [comment]
Non pas d'évolution et rien de prévu sur le sujet.

**Comment by camillemonchicourt** [comment]
Intégré dans la 1.5.0 avec un paramètre pour activer ou non le masque, et le styler comme souhaité.
