### ISSUE TITLE
Ajout d'un module "fiche par groupe"

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/GeoNature-atlas#91]
Une idée qui m'a été remontée, il serait bien d'avoir un module pour créer une fiche pour un groupe donné. 

Ainsi si je recherche insectes, les données insectes sont poolées et des cartes de prospections apparaissent, idem à l'échelle odonate etc. Ca permet de voir les défauts de prospections à de grandes échelles, notamment pour des assos où les prospections dépendent souvent du lieu d'habitation des amateurs de tel ou tel taxon. 

A bientôt!
Donovan

**Comment by camillemonchicourt** [comment]
On a déjà les fiches par groupe : http://biodiversite.ecrins-parcnational.fr/groupe/Gastéropodes

Mais comme pour les fiches par rang taxonomique il n'y a pas de carte.

**Comment by DonovanMaillard** [comment]
Yep, c'est justement cette carte, les diagrammes altitudinaux et saisonniers qui seraient demandés ;) et une possibilité de mettre des médias à l'échelle du groupe je pense : listes rouges etc par exemple

**Comment by camillemonchicourt** [comment]
OK à creuser. Les listes doivent peut être évoluer. 
Mais attention, l'atlas est un outil de restitution externe, pas interne.

Si il faut des outils pour analyser et orienter les prospections, c'est dans GeoNature, pas dans l'atlas.

**Comment by sylvain-m** [comment]
Suite à la prise en main progressive de notre GeoNature, j'abonde dans le sens de Donovan.
Pour les fiches par groupe (et je parle bien de l'Atlas public, pas de la synthèse), il serait bon de disposer d'Atlas spécifiques, avec des cartes par mailles qui permettent de faire figurer : 
- le nombre d'espèces dans la maille, avec classes couleurs correspondantes (les cartes quantitatives actuelles se basent sur le "nombre d'observations" uniquement, et pas sur le nombre d'espèces).
- des statistiques plus poussées (évolution du nombre d'espèces dans le temps par exemple).

Si vous ne vous moquez pas de mon code source dégueulasse (je suis pas développeur !), j'ai fait ça dans le cadre d'un projet bénévole d'Atlas des Noctuelles en Basse Normandie : http://symont.pagesperso-orange.fr/lepido-bn/carto.html (c'est du Google Maps car j'avais commencé en 2008 sans rien y connaitre en OpenSource...).

Je peux tenter de m'occuper des requêtes SQL nécessaires de mon côté (dès que je me serai un peu plus approprié le modèle de données), voire un peu plus.

C'est une demande assez forte de mes collègues, que je partage et qui (je le répète), ne concernerait pas que la restitution interne (Synthèse de GeoNature), mais bien l'Atlas public.

**Comment by DonovanMaillard** [comment]
Juste en complément : 

Effectivement il y a cet intérêt de cibler les prospections etc, et donc ca concerne geonature et on peut déjà le faire ;)

Mais pour le grand public : voir les zones les mieux connues, les plus riches, voir si la richesse faible correspond à un faible niveau de prospection ou à une vraie pauvreté des milieux etc, ca peut aussi être un rendu intéressant. Alors biensur, on sort du "grand public" le plus novice... mais pour un paquet de particuliers naturalistes, ces infos ont du sens ;)  Et pour un financeur, idem : c'est des infos qui donnent une idée de l'avancée d'un atlas ;)

**Comment by camillemonchicourt** [comment]
Actuellement pour les rangs et les groupes on affiche la liste des espèces observées. 

Est-ce que ces fiches GROUPES devraient garder cette approche de liste d'espèce en y ajoutant une carte et des graphes (un peu comme les fiches communes) ? 
Ou devraient-elles plutôt se baser sur l'exemple des fiches espèces ? 

Pour info, pour les rangs, ils sont affichés sous forme de liste, mais en remplaçant liste par espèce dans l'URL on accès à la fiche du rang qui agglomère toutes les observations des espèces du rang. 

Exemple : http://biodiversite.ecrins-parcnational.fr/espece/185214
ou encore http://biodiversite.ecrins-parcnational.fr/espece/186206

**Comment by sylvain-m** [comment]
> On peut faire ça à n'importe quel rang ! :-)

Super !!!
Je découvre ces fiches espèces "rangs".
Ce qu'il faudrait effectivement, c'est qu'ils soient plus en valeur sur les rangs taxonomiques souhaités, et surtout qu'ils ne se limitent pas à des statistiques "nombre d'observation", mais qu'il y ait la stat du nombre d'espèces du rang dans la maille (et potentiellement d'autres stats / graph spécifiques au rang).

**Comment by camillemonchicourt** [comment]
C'est une fonctionnalité cachée et pas forcément volontaire au départ ! :-)
C'est générique, c'est une fiche espèce mais affichée au niveau d'un autre rang que l'espèce. 
Dans la conf, on peut paramétrer à quel rang on passe de la LISTE d’espèce à la FICHE qui agglomère tous les enfants. 
Mais avec l'URL on peut contourner ce paramètre.

**Comment by sylvain-m** [comment]
L'idéal serait de coupler les infos de la fiche "Liste" aux infos de la fiche "rang", dans une même URL, avec des statistiques plus poussées.
